from Sass.completions import values as v

# CSS Tag List
tag = [
    ("a\tTag", 'a'),
    ("abbr\tTag", 'abbr'),
    ("acronym\tTag", 'acronym'),
    ("address\tTag", 'address'),
    ("area\tTag", 'area'),
    ("article\tTag", 'article'),
    ("aside\tTag", 'aside'),
    ("audio\tTag", 'audio'),
    ("b\tTag", 'b'),
    ("base\tTag", 'base'),
    ("bdi\tTag", 'bdi'),
    ("bdo\tTag", 'bdo'),
    ("big\tTag", 'big'),
    ("blockquote\tTag", 'blockquote'),
    ("body\tTag", 'body'),
    ("br\tTag", 'br'),
    ("button\tTag", 'button'),
    ("canvas\tTag", 'canvas'),
    ("caption\tTag", 'caption'),
    ("cite\tTag", 'cite'),
    ("code\tTag", 'code'),
    ("col\tTag", 'col'),
    ("colgroup\tTag", 'colgroup'),
    ("command\tTag", 'command'),
    ("datalist\tTag", 'datalist'),
    ("dd\tTag", 'dd'),
    ("del\tTag", 'del'),
    ("details\tTag", 'details'),
    ("div\tTag", 'div'),
    ("dfn\tTag", 'dfn'),
    ("dialog\tTag", 'dialog'),
    ("dl\tTag", 'dl'),
    ("dt\tTag", 'dt'),
    ("em\tTag", 'em'),
    ("embed\tTag", 'embed'),
    ("fieldset\tTag", 'fieldset'),
    ("figcaption\tTag", 'figcaption'),
    ("figure\tTag", 'figure'),
    ("footer\tTag", 'footer'),
    ("form\tTag", 'form'),
    ("frame\tTag", 'frame'),
    ("frameset\tTag", 'frameset'),
    ("h1\tTag", 'h1'),
    ("head\tTag", 'head'),
    ("header\tTag", 'header'),
    ("hr\tTag", 'hr'),
    ("html\tTag", 'html'),
    ("i\tTag", 'i'),
    ("iframe\tTag", 'iframe'),
    ("img\tTag", 'img'),
    ("input\tTag", 'input'),
    ("ins\tTag", 'ins'),
    ("kbd\tTag", 'kbd'),
    ("keygen\tTag", 'keygen'),
    ("label\tTag", 'label'),
    ("legend\tTag", 'legend'),
    ("li\tTag", 'li'),
    ("link\tTag", 'link'),
    ("main\tTag", 'main'),
    ("map\tTag", 'map'),
    ("mark\tTag", 'mark'),
    ("menu\tTag", 'menu'),
    ("menuitem\tTag", 'menuitem'),
    ("meta\tTag", 'meta'),
    ("meter\tTag", 'meter'),
    ("nav\tTag", 'nav'),
    ("noframes\tTag", 'noframes'),
    ("noscript\tTag", 'noscript'),
    ("object\tTag", 'object'),
    ("ol\tTag", 'ol'),
    ("optgroup\tTag", 'optgroup'),
    ("option\tTag", 'option'),
    ("output\tTag", 'output'),
    ("p\tTag", 'p'),
    ("param\tTag", 'param'),
    ("pre\tTag", 'pre'),
    ("progress\tTag", 'progress'),
    ("q\tTag", 'q'),
    ("rp\tTag", 'rp'),
    ("rt\tTag", 'rt'),
    ("ruby\tTag", 'ruby'),
    ("samp\tTag", 'samp'),
    ("script\tTag", 'script'),
    ("section\tTag", 'section'),
    ("select\tTag", 'select'),
    ("small\tTag", 'small'),
    ("source\tTag", 'source'),
    ("span\tTag", 'span'),
    ("strong\tTag", 'strong'),
    ("style\tTag", 'style'),
    ("sub\tTag", 'sub'),
    ("summary\tTag", 'summary'),
    ("sup\tTag", 'sup'),
    ("table\tTag", 'table'),
    ("tbody\tTag", 'tbody'),
    ("td\tTag", 'td'),
    ("textarea\tTag", 'textarea'),
    ("tfoot\tTag", 'tfoot'),
    ("th\tTag", 'th'),
    ("thead\tTag", 'thead'),
    ("time\tTag", 'time'),
    ("title\tTag", 'title'),
    ("tr\tTag", 'tr'),
    ("track\tTag", 'track'),
    ("tt\tTag", 'tt'),
    ("ul\tTag", 'ul'),
    ("var\tTag", 'var'),
    ("video\tTag", 'video'),
    ("wbr\tTag", 'wbr'),

    ("from\tKeyframes", 'from {$1}'),
    ("to\tKeyframes", 'to {$1}'),

    ("svg\tSVG", 'svg'),
    ("desc\tSVG", 'desc'),
    ("defs\tSVG", 'defs'),
    ("g\tSVG", 'g'),
    ("line\tSVG", 'line'),
    ("rect\tSVG", 'rect'),
    ("circle\tSVG", 'circle'),
    ("ellipse\tSVG", 'ellipse'),
    ("polyline\tSVG", 'polyline'),
    ("polygon\tSVG", 'polygon'),
    ("path\tSVG", 'path'),
    ("text\tSVG", 'text'),
    ("tspan\tSVG", 'tspan'),
    ("use\tSVG", 'use'),
    ("clipPath\tSVG", 'clipPath'),
    ("pattern\tSVG", 'pattern'),
    ("symbol\tSVG", 'symbol'),
    ("linearGadient\tSVG", 'linearGadient'),
    ("radialGradient\tSVG", 'radialGradient'),
    ("stop\tSVG", 'stop')
]

# CSS Style List
names = [
    ("additive-symbols\tStyle", 'additive-symbols:${0};'),
    ("align-content\tStyle", 'align-content:${0};'),
    ("align-items\tStyle", 'align-items:${0};'),
    ("align-self\tStyle", 'align-self:${0};'),
    ("alignment\tStyle", 'alignment:${0};'),
    ("alignment-adjust\tStyle", 'alignment-adjust:${0};'),
    ("alignment-baseline\tStyle", 'alignment-baseline:${0};'),
    ("all\tStyle", 'all:${0};'),
    ("animation\tStyle", 'animation:${0};'),
    ("animation-delay\tStyle", 'animation-delay:${0};'),
    ("animation-direction\tStyle", 'animation-direction:${0};'),
    ("animation-duration\tStyle", 'animation-duration:${0};'),
    ("animation-fill-mode\tStyle", 'animation-fill-mode:${0};'),
    ("animation-iteration-count\tStyle", 'animation-iteration-count:${0};'),
    ("animation-name\tStyle", 'animation-name:${0};'),
    ("animation-play-state\tStyle", 'animation-play-state:${0};'),
    ("animation-timing-function\tStyle", 'animation-timing-function:${0};'),
    ("backface-visibility\tStyle", 'backface-visibility:${0};'),
    ("background\tStyle", 'background:${0};'),
    ("background-attachment\tStyle", 'background-attachment:${0};'),
    ("background-blend-mode\tStyle", 'background-blend-mode:${0};'),
    ("background-clip\tStyle", 'background-clip:${0};'),
    ("background-color\tStyle", 'background-color:${0};'),
    ("background-image\tStyle", 'background-image:${0};'),
    ("background-origin\tStyle", 'background-origin:${0};'),
    ("background-position\tStyle", 'background-position:${0};'),
    ("background-repeat\tStyle", 'background-repeat:${0};'),
    ("background-size\tStyle", 'background-size:${0};'),
    ("baseline-shift\tStyle", 'baseline-shift:${0};'),
    ("bleed\tStyle", 'bleed:${0};'),
    ("bookmark-label\tStyle", 'bookmark-label:${0};'),
    ("bookmark-level\tStyle", 'bookmark-level:${0};'),
    ("bookmark-state\tStyle", 'bookmark-state:${0};'),
    ("border\tStyle", 'border:${0};'),
    ("border-bottom\tStyle", 'border-bottom:${0};'),
    ("border-bottom-color\tStyle", 'border-bottom-color:${0};'),
    ("border-bottom-left-radius\tStyle", 'border-bottom-left-radius:${0};'),
    ("border-bottom-right-radius\tStyle", 'border-bottom-right-radius:${0};'),
    ("border-bottom-style\tStyle", 'border-bottom-style:${0};'),
    ("border-bottom-width\tStyle", 'border-bottom-width:${0};'),
    ("border-clip\tStyle", 'border-clip:${0};'),
    ("border-clip-bottom\tStyle", 'border-clip-bottom:${0};'),
    ("border-clip-left\tStyle", 'border-clip-left:${0};'),
    ("border-clip-right\tStyle", 'border-clip-right:${0};'),
    ("border-clip-top\tStyle", 'border-clip-top:${0};'),
    ("border-collapse\tStyle", 'border-collapse:${0};'),
    ("border-color\tStyle", 'border-color:${0};'),
    ("border-image\tStyle", 'border-image:${0};'),
    ("border-image-outset\tStyle", 'border-image-outset:${0};'),
    ("border-image-repeat\tStyle", 'border-image-repeat:${0};'),
    ("border-image-slice\tStyle", 'border-image-slice:${0};'),
    ("border-image-source\tStyle", 'border-image-source:${0};'),
    ("border-image-width\tStyle", 'border-image-width:${0};'),
    ("border-left\tStyle", 'border-left:${0};'),
    ("border-left-color\tStyle", 'border-left-color:${0};'),
    ("border-left-style\tStyle", 'border-left-style:${0};'),
    ("border-left-width\tStyle", 'border-left-width:${0};'),
    ("border-limit\tStyle", 'border-limit:${0};'),
    ("border-radius\tStyle", 'border-radius:${0};'),
    ("border-right\tStyle", 'border-right:${0};'),
    ("border-right-color\tStyle", 'border-right-color:${0};'),
    ("border-right-style\tStyle", 'border-right-style:${0};'),
    ("border-right-width\tStyle", 'border-right-width:${0};'),
    ("border-spacing\tStyle", 'border-spacing:${0};'),
    ("border-style\tStyle", 'border-style:${0};'),
    ("border-top\tStyle", 'border-top:${0};'),
    ("border-top-color\tStyle", 'border-top-color:${0};'),
    ("border-top-left-radius\tStyle", 'border-top-left-radius:${0};'),
    ("border-top-right-radius\tStyle", 'border-top-right-radius:${0};'),
    ("border-top-style\tStyle", 'border-top-style:${0};'),
    ("border-top-width\tStyle", 'border-top-width:${0};'),
    ("border-width\tStyle", 'border-width:${0};'),
    ("bottom\tStyle", 'bottom:${0};'),
    ("box-decoration-break\tStyle", 'box-decoration-break:${0};'),
    ("box-shadow\tStyle", 'box-shadow:${0};'),
    ("box-sizing\tStyle", 'box-sizing:${0};'),
    ("box-snap\tStyle", 'box-snap:${0};'),
    ("box-suppress\tStyle", 'box-suppress:${0};'),
    ("break-after\tStyle", 'break-after:${0};'),
    ("break-before\tStyle", 'break-before:${0};'),
    ("break-inside\tStyle", 'break-inside:${0};'),
    ("caption-side\tStyle", 'caption-side:${0};'),
    ("chains\tStyle", 'chains:${0};'),
    ("child-align\tStyle", 'child-align:${0};'),
    ("clear\tStyle", 'clear:${0};'),
    ("clear-after\tStyle", 'clear-after:${0};'),
    ("clear-side\tStyle", 'clear-side:${0};'),
    ("clip-path\tStyle", 'clip-path:${0};'),
    ("clip-rule\tStyle", 'clip-rule:${0};'),
    ("color\tStyle", 'color:${0};'),
    ("color-adjust\tStyle", 'color-adjust:${0};'),
    ("color-correction\tStyle", 'color-correction:${0};'),
    ("color-interpolation\tStyle", 'color-interpolation:${0};'),
    ("color-interpolation-filters\tStyle", 'color-interpolation-filters:${0};'),
    ("column-count\tStyle", 'column-count:${0};'),
    ("column-fill\tStyle", 'column-fill:${0};'),
    ("column-gap\tStyle", 'column-gap:${0};'),
    ("column-rule\tStyle", 'column-rule:${0};'),
    ("column-rule-color\tStyle", 'column-rule-color:${0};'),
    ("column-rule-style\tStyle", 'column-rule-style:${0};'),
    ("column-rule-width\tStyle", 'column-rule-width:${0};'),
    ("column-span\tStyle", 'column-span:${0};'),
    ("column-width\tStyle", 'column-width:${0};'),
    ("columns\tStyle", 'columns:${0};'),
    ("contain\tStyle", 'contain:${0};'),
    ("content\tStyle", 'content:${0};'),
    ("corner-shape\tStyle", 'corner-shape:${0};'),
    ("corners\tStyle", 'corners:${0};'),
    ("counter-increment\tStyle", 'counter-increment:${0};'),
    ("counter-reset\tStyle", 'counter-reset:${0};'),
    ("counter-set\tStyle", 'counter-set:${0};'),
    ("cue\tStyle", 'cue:${0};'),
    ("cue-after\tStyle", 'cue-after:${0};'),
    ("cue-before\tStyle", 'cue-before:${0};'),
    ("cursor\tStyle", 'cursor:${0};'),
    ("direction\tStyle", 'direction:${0};'),
    ("display\tStyle", 'display:${0};'),
    ("display-inside\tStyle", 'display-inside:${0};'),
    ("display-list\tStyle", 'display-list:${0};'),
    ("display-outside\tStyle", 'display-outside:${0};'),
    ("dominant-baseline\tStyle", 'dominant-baseline:${0};'),
    ("empty-cells\tStyle", 'empty-cells:${0};'),
    ("fallback\tStyle", 'fallback:${0};'),
    ("filter\tStyle", 'filter:${0};'),
    ("flex\tStyle", 'flex:${0};'),
    ("flex-basis\tStyle", 'flex-basis:${0};'),
    ("flex-direction\tStyle", 'flex-direction:${0};'),
    ("flex-flow\tStyle", 'flex-flow:${0};'),
    ("flex-grow\tStyle", 'flex-grow:${0};'),
    ("flex-shrink\tStyle", 'flex-shrink:${0};'),
    ("flex-wrap\tStyle", 'flex-wrap:${0};'),
    ("float\tStyle", 'float:${0};'),
    ("float-defer-column\tStyle", 'float-defer-column:${0};'),
    ("float-defer-page\tStyle", 'float-defer-page:${0};'),
    ("float-displace\tStyle", 'float-displace:${0};'),
    ("float-offset\tStyle", 'float-offset:${0};'),
    ("float-wrap\tStyle", 'float-wrap:${0};'),
    ("flood-color\tStyle", 'flood-color:${0};'),
    ("flood-opacity\tStyle", 'flood-opacity:${0};'),
    ("flow\tStyle", 'flow:${0};'),
    ("flow-from\tStyle", 'flow-from:${0};'),
    ("flow-into\tStyle", 'flow-into:${0};'),
    ("font\tStyle", 'font:${0};'),
    ("font-family\tStyle", 'font-family:${0};'),
    ("font-feature-settings\tStyle", 'font-feature-settings:${0};'),
    ("font-kerning\tStyle", 'font-kerning:${0};'),
    ("font-language-override\tStyle", 'font-language-override:${0};'),
    ("font-size\tStyle", 'font-size:${0};'),
    ("font-size-adjust\tStyle", 'font-size-adjust:${0};'),
    ("font-stretch\tStyle", 'font-stretch:${0};'),
    ("font-style\tStyle", 'font-style:${0};'),
    ("font-synthesis\tStyle", 'font-synthesis:${0};'),
    ("font-variant\tStyle", 'font-variant:${0};'),
    ("font-variant-alternates\tStyle", 'font-variant-alternates:${0};'),
    ("font-variant-caps\tStyle", 'font-variant-caps:${0};'),
    ("font-variant-east-asian\tStyle", 'font-variant-east-asian:${0};'),
    ("font-variant-ligatures\tStyle", 'font-variant-ligatures:${0};'),
    ("font-variant-numeric\tStyle", 'font-variant-numeric:${0};'),
    ("font-variant-position\tStyle", 'font-variant-position:${0};'),
    ("font-weight\tStyle", 'font-weight:${0};'),
    ("footnote-display\tStyle", 'footnote-display:${0};'),
    ("footnote-policy\tStyle", 'footnote-policy:${0};'),
    ("grid\tStyle", 'grid:${0};'),
    ("grid-area\tStyle", 'grid-area:${0};'),
    ("grid-auto-columns\tStyle", 'grid-auto-columns:${0};'),
    ("grid-auto-flow\tStyle", 'grid-auto-flow:${0};'),
    ("grid-auto-rows\tStyle", 'grid-auto-rows:${0};'),
    ("grid-column\tStyle", 'grid-column:${0};'),
    ("grid-column-end\tStyle", 'grid-column-end:${0};'),
    ("grid-column-start\tStyle", 'grid-column-start:${0};'),
    ("grid-row\tStyle", 'grid-row:${0};'),
    ("grid-row-end\tStyle", 'grid-row-end:${0};'),
    ("grid-row-start\tStyle", 'grid-row-start:${0};'),
    ("grid-template\tStyle", 'grid-template:${0};'),
    ("grid-template-areas\tStyle", 'grid-template-areas:${0};'),
    ("grid-template-columns\tStyle", 'grid-template-columns:${0};'),
    ("grid-template-rows\tStyle", 'grid-template-rows:${0};'),
    ("hanging-punctuation\tStyle", 'hanging-punctuation:${0};'),
    ("height\tStyle", 'height:${0};'),
    ("hyphens\tStyle", 'hyphens:${0};'),
    ("image-orientation\tStyle", 'image-orientation:${0};'),
    ("image-resolution\tStyle", 'image-resolution:${0};'),
    ("indent-edge-reset\tStyle", 'indent-edge-reset:${0};'),
    ("initial-letter\tStyle", 'initial-letter:${0};'),
    ("initial-letter-align\tStyle", 'initial-letter-align:${0};'),
    ("inline-box-align\tStyle", 'inline-box-align:${0};'),
    ("isolation\tStyle", 'isolation:${0};'),
    ("justify-content\tStyle", 'justify-content:${0};'),
    ("justify-items\tStyle", 'justify-items:${0};'),
    ("justify-self\tStyle", 'justify-self:${0};'),
    ("left\tStyle", 'left:${0};'),
    ("letter-spacing\tStyle", 'letter-spacing:${0};'),
    ("lighting-color\tStyle", 'lighting-color:${0};'),
    ("line-break\tStyle", 'line-break:${0};'),
    ("line-grid\tStyle", 'line-grid:${0};'),
    ("line-height\tStyle", 'line-height:${0};'),
    ("line-snap\tStyle", 'line-snap:${0};'),
    ("line-stacking\tStyle", 'line-stacking:${0};'),
    ("line-stacking-ruby\tStyle", 'line-stacking-ruby:${0};'),
    ("line-stacking-shift\tStyle", 'line-stacking-shift:${0};'),
    ("line-stacking-strategy\tStyle", 'line-stacking-strategy:${0};'),
    ("list-style\tStyle", 'list-style:${0};'),
    ("list-style-image\tStyle", 'list-style-image:${0};'),
    ("list-style-position\tStyle", 'list-style-position:${0};'),
    ("list-style-type\tStyle", 'list-style-type:${0};'),
    ("margin\tStyle", 'margin:${0};'),
    ("margin-bottom\tStyle", 'margin-bottom:${0};'),
    ("margin-left\tStyle", 'margin-left:${0};'),
    ("margin-right\tStyle", 'margin-right:${0};'),
    ("margin-top\tStyle", 'margin-top:${0};'),
    ("marker-side\tStyle", 'marker-side:${0};'),
    ("marks\tStyle", 'marks:${0};'),
    ("mask\tStyle", 'mask:${0};'),
    ("mask-border\tStyle", 'mask-border:${0};'),
    ("mask-border-mode\tStyle", 'mask-border-mode:${0};'),
    ("mask-border-outset\tStyle", 'mask-border-outset:${0};'),
    ("mask-border-repeat\tStyle", 'mask-border-repeat:${0};'),
    ("mask-border-slice\tStyle", 'mask-border-slice:${0};'),
    ("mask-border-source\tStyle", 'mask-border-source:${0};'),
    ("mask-border-width\tStyle", 'mask-border-width:${0};'),
    ("mask-clip\tStyle", 'mask-clip:${0};'),
    ("mask-composite\tStyle", 'mask-composite:${0};'),
    ("mask-image\tStyle", 'mask-image:${0};'),
    ("mask-mode\tStyle", 'mask-mode:${0};'),
    ("mask-origin\tStyle", 'mask-origin:${0};'),
    ("mask-position\tStyle", 'mask-position:${0};'),
    ("mask-repeat\tStyle", 'mask-repeat:${0};'),
    ("mask-size\tStyle", 'mask-size:${0};'),
    ("mask-type\tStyle", 'mask-type:${0};'),
    ("max-height\tStyle", 'max-height:${0};'),
    ("max-lines\tStyle", 'max-lines:${0};'),
    ("max-width\tStyle", 'max-width:${0};'),
    ("max-zoom\tStyle", 'max-zoom:${0};'),
    ("min-height\tStyle", 'min-height:${0};'),
    ("min-width\tStyle", 'min-width:${0};'),
    ("min-zoom\tStyle", 'min-zoom:${0};'),
    ("mix-blend-mode\tStyle", 'mix-blend-mode:${0};'),
    ("motion\tStyle", 'motion:${0};'),
    ("motion-offset\tStyle", 'motion-offset:${0};'),
    ("motion-path\tStyle", 'motion-path:${0};'),
    ("motion-rotation\tStyle", 'motion-rotation:${0};'),
    ("nav-down\tStyle", 'nav-down:${0};'),
    ("nav-left\tStyle", 'nav-left:${0};'),
    ("nav-right\tStyle", 'nav-right:${0};'),
    ("nav-up\tStyle", 'nav-up:${0};'),
    ("negative\tStyle", 'negative:${0};'),
    ("object-fit\tStyle", 'object-fit:${0};'),
    ("object-position\tStyle", 'object-position:${0};'),
    ("offset-after\tStyle", 'offset-after:${0};'),
    ("offset-before\tStyle", 'offset-before:${0};'),
    ("offset-end\tStyle", 'offset-end:${0};'),
    ("offset-start\tStyle", 'offset-start:${0};'),
    ("opacity\tStyle", 'opacity:${0};'),
    ("order\tStyle", 'order:${0};'),
    ("orientation\tStyle", 'orientation:${0};'),
    ("orphans\tStyle", 'orphans:${0};'),
    ("outline\tStyle", 'outline:${0};'),
    ("outline-color\tStyle", 'outline-color:${0};'),
    ("outline-offset\tStyle", 'outline-offset:${0};'),
    ("outline-style\tStyle", 'outline-style:${0};'),
    ("outline-width\tStyle", 'outline-width:${0};'),
    ("overflow\tStyle", 'overflow:${0};'),
    ("overflow-style\tStyle", 'overflow-style:${0};'),
    ("overflow-wrap\tStyle", 'overflow-wrap:${0};'),
    ("overflow-x\tStyle", 'overflow-x:${0};'),
    ("overflow-y\tStyle", 'overflow-y:${0};'),
    ("pad\tStyle", 'pad:${0};'),
    ("padding\tStyle", 'padding:${0};'),
    ("padding-bottom\tStyle", 'padding-bottom:${0};'),
    ("padding-left\tStyle", 'padding-left:${0};'),
    ("padding-right\tStyle", 'padding-right:${0};'),
    ("padding-top\tStyle", 'padding-top:${0};'),
    ("page\tStyle", 'page:${0};'),
    ("page-policy\tStyle", 'page-policy:${0};'),
    ("pause\tStyle", 'pause:${0};'),
    ("pause-after\tStyle", 'pause-after:${0};'),
    ("pause-before\tStyle", 'pause-before:${0};'),
    ("perspective\tStyle", 'perspective:${0};'),
    ("perspective-origin\tStyle", 'perspective-origin:${0};'),
    ("pointer-events\tStyle", 'pointer-events:${0};'),
    ("position\tStyle", 'position:${0};'),
    ("prefix\tStyle", 'prefix:${0};'),
    ("quotes\tStyle", 'quotes:${0};'),
    ("range\tStyle", 'range:${0};'),
    ("region-fragment\tStyle", 'region-fragment:${0};'),
    ("resize\tStyle", 'resize:${0};'),
    ("resolution\tStyle", 'resolution:${0};'),
    ("rest\tStyle", 'rest:${0};'),
    ("rest-after\tStyle", 'rest-after:${0};'),
    ("rest-before\tStyle", 'rest-before:${0};'),
    ("right\tStyle", 'right:${0};'),
    ("rotation\tStyle", 'rotation:${0};'),
    ("rotation-point\tStyle", 'rotation-point:${0};'),
    ("ruby-align\tStyle", 'ruby-align:${0};'),
    ("ruby-merge\tStyle", 'ruby-merge:${0};'),
    ("ruby-position\tStyle", 'ruby-position:${0};'),
    ("running\tStyle", 'running:${0};'),
    ("scroll-snap-coordinate\tStyle", 'scroll-snap-coordinate:${0};'),
    ("scroll-snap-destination\tStyle", 'scroll-snap-destination:${0};'),
    ("scroll-snap-points-x\tStyle", 'scroll-snap-points-x:${0};'),
    ("scroll-snap-points-y\tStyle", 'scroll-snap-points-y:${0};'),
    ("scroll-snap-type\tStyle", 'scroll-snap-type:${0};'),
    ("shape-image-threshold\tStyle", 'shape-image-threshold:${0};'),
    ("shape-margin\tStyle", 'shape-margin:${0};'),
    ("shape-outside\tStyle", 'shape-outside:${0};'),
    ("size\tStyle", 'size:${0};'),
    ("speak\tStyle", 'speak:${0};'),
    ("speak-as\tStyle", 'speak-as:${0};'),
    ("src\tStyle", 'src:${0};'),
    ("string-set\tStyle", 'string-set:${0};'),
    ("suffix\tStyle", 'suffix:${0};'),
    ("symbols\tStyle", 'symbols:${0};'),
    ("system\tStyle", 'system:${0};'),
    ("tab-size\tStyle", 'tab-size:${0};'),
    ("table-layout\tStyle", 'table-layout:${0};'),
    ("text-align\tStyle", 'text-align:${0};'),
    ("text-align-last\tStyle", 'text-align-last:${0};'),
    ("text-combine-upright\tStyle", 'text-combine-upright:${0};'),
    ("text-decoration\tStyle", 'text-decoration:${0};'),
    ("text-decoration-color\tStyle", 'text-decoration-color:${0};'),
    ("text-decoration-line\tStyle", 'text-decoration-line:${0};'),
    ("text-decoration-skip\tStyle", 'text-decoration-skip:${0};'),
    ("text-decoration-style\tStyle", 'text-decoration-style:${0};'),
    ("text-emphasis\tStyle", 'text-emphasis:${0};'),
    ("text-emphasis-color\tStyle", 'text-emphasis-color:${0};'),
    ("text-emphasis-position\tStyle", 'text-emphasis-position:${0};'),
    ("text-emphasis-style\tStyle", 'text-emphasis-style:${0};'),
    ("text-height\tStyle", 'text-height:${0};'),
    ("text-indent\tStyle", 'text-indent:${0};'),
    ("text-justify\tStyle", 'text-justify:${0};'),
    ("text-orientation\tStyle", 'text-orientation:${0};'),
    ("text-overflow\tStyle", 'text-overflow:${0};'),
    ("text-shadow\tStyle", 'text-shadow:${0};'),
    ("text-transform\tStyle", 'text-transform:${0};'),
    ("text-underline-position\tStyle", 'text-underline-position:${0};'),
    ("top\tStyle", 'top:${0};'),
    ("transform\tStyle", 'transform:${0};'),
    ("transform-box\tStyle", 'transform-box:${0};'),
    ("transform-origin\tStyle", 'transform-origin:${0};'),
    ("transform-style\tStyle", 'transform-style:${0};'),
    ("transition\tStyle", 'transition:${0};'),
    ("transition-delay\tStyle", 'transition-delay:${0};'),
    ("transition-duration\tStyle", 'transition-duration:${0};'),
    ("transition-property\tStyle", 'transition-property:${0};'),
    ("transition-timing-function\tStyle", 'transition-timing-function:${0};'),
    ("unicode-bidi\tStyle", 'unicode-bidi:${0};'),
    ("unicode-range\tStyle", 'unicode-range:${0};'),
    ("user-zoom\tStyle", 'user-zoom:${0};'),
    ("vertical-align\tStyle", 'vertical-align:${0};'),
    ("visibility\tStyle", 'visibility:${0};'),
    ("voice-balance\tStyle", 'voice-balance:${0};'),
    ("voice-duration\tStyle", 'voice-duration:${0};'),
    ("voice-family\tStyle", 'voice-family:${0};'),
    ("voice-pitch\tStyle", 'voice-pitch:${0};'),
    ("voice-range\tStyle", 'voice-range:${0};'),
    ("voice-rate\tStyle", 'voice-rate:${0};'),
    ("voice-stress\tStyle", 'voice-stress:${0};'),
    ("voice-volume\tStyle", 'voice-volume:${0};'),
    ("white-space\tStyle", 'white-space:${0};'),
    ("widows\tStyle", 'widows:${0};'),
    ("width\tStyle", 'width:${0};'),
    ("will-change\tStyle", 'will-change:${0};'),
    ("word-break\tStyle", 'word-break:${0};'),
    ("word-spacing\tStyle", 'word-spacing:${0};'),
    ("word-wrap\tStyle", 'word-wrap:${0};'),
    ("wrap-flow\tStyle", 'wrap-flow:${0};'),
    ("wrap-through\tStyle", 'wrap-through:${0};'),
    ("writing-mode\tStyle", 'writing-mode:${0};'),
    ("z-index\tStyle", 'z-index:${0};'),
    ("zoom\tStyle", 'zoom:${0}; '),

    ("fill\tSVG", 'fill:$1;'),
    ("fill-opacity\tSVG", 'fill-opacity:$1;'),
    ("fill-rule\tSVG", 'fill-rule:$1;'),
    ("stroke\tSVG", 'stroke:$1;'),
    ("stroke-width\tSVG", 'stroke-width:$1;'),
    ("stroke-dasharray\tSVG", 'stroke-dasharray:$1;'),
    ("stroke-dashoffset\tSVG", 'stroke-dashoffset:$1;'),
    ("stroke-linecap\tSVG", 'stroke-linecap:$1;'),
    ("stroke-linejoin\tSVG", 'stroke-linejoin:$1;'),
    ("stroke-miterlimit\tSVG", 'stroke-miterlimit:$1;'),
    ("stroke-opacity\tSVG", 'stroke-opacity:$1;')
]

# CSS Value List
value_for_name = {
    'additive-symbols': v.image,
    'align-content': [("auto\tValue", 'auto'), ("baseline\tValue", 'baseline'), ("center\tValue", 'center'), ("end\tValue", 'end'), ("flex-end\tValue", 'flex-end'), ("flex-start\tValue", 'flex-start'), ("last-baseline\tValue", 'last-baseline'), ("left\tValue", 'left'), ("right\tValue", 'right'), ("safe\tValue", 'safe'), ("space-around\tValue", 'space-around'), ("space-between\tValue", 'space-between'), ("space-evenly\tValue", 'space-evenly'), ("start\tValue", 'start'), ("stretch\tValue", 'stretch'), ("true\tValue", 'true')],
    'align-items': [("auto\tValue", 'auto'), ("baseline\tValue", 'baseline'), ("center\tValue", 'center'), ("end\tValue", 'end'), ("flex-end\tValue", 'flex-end'), ("flex-start\tValue", 'flex-start'), ("last-baseline\tValue", 'last-baseline'), ("left\tValue", 'left'), ("right\tValue", 'right'), ("safe\tValue", 'safe'), ("self-end\tValue", 'self-end'), ("self-start\tValue", 'self-start'), ("start\tValue", 'start'), ("stretch\tValue", 'stretch'), ("true\tValue", 'true')],
    'align-self': [("auto\tValue", 'auto'), ("baseline\tValue", 'baseline'), ("center\tValue", 'center'), ("end\tValue", 'end'), ("flex-end\tValue", 'flex-end'), ("flex-start\tValue", 'flex-start'), ("last-baseline\tValue", 'last-baseline'), ("left\tValue", 'left'), ("right\tValue", 'right'), ("safe\tValue", 'safe'), ("self-end\tValue", 'self-end'), ("self-start\tValue", 'self-start'), ("start\tValue", 'start'), ("stretch\tValue", 'stretch'), ("true\tValue", 'true')],
    'alignment': [("bottom\tValue", 'bottom'), ("center\tValue", 'center'), ("left\tValue", 'left'), ("right\tValue", 'right'), ("top\tValue", 'top')],
    'alignment-adjust': [("alphabetic\tValue", 'alphabetic'), ("auto\tValue", 'auto'), ("baseline\tValue", 'baseline'), ("central\tValue", 'central'), ("hanging\tValue", 'hanging'), ("ideographic\tValue", 'ideographic'), ("mathematical\tValue", 'mathematical'), ("middle\tValue", 'middle'), ("over-edge\tValue", 'over-edge'), ("text-over-edge\tValue", 'text-over-edge'), ("text-under-edge\tValue", 'text-under-edge'), ("under-edge\tValue", 'under-edge')],
    'alignment-baseline': [("alphabetic\tValue", 'alphabetic'), ("baseline\tValue", 'baseline'), ("central\tValue", 'central'), ("hanging\tValue", 'hanging'), ("ideographic\tValue", 'ideographic'), ("mathematical\tValue", 'mathematical'), ("middle\tValue", 'middle'), ("over-edge\tValue", 'over-edge'), ("text-over-edge\tValue", 'text-over-edge'), ("text-under-edge\tValue", 'text-under-edge'), ("under-edge\tValue", 'under-edge'), ("use-script\tValue", 'use-script')],
    'animation': [("alternate\tValue", 'alternate'), ("alternate-reverse\tValue", 'alternate-reverse'), ("backwards\tValue", 'backwards'), ("both\tValue", 'both'), ("forwards\tValue", 'forwards'), ("infinite\tValue", 'infinite'), ("none\tValue", 'none'), ("normal\tValue", 'normal'), ("paused\tValue", 'paused'), ("reverse\tValue", 'reverse'), ("running\tValue", 'running')] + v.timing_function,
    'animation-direction': [("alternate\tValue", 'alternate'), ("alternate-reverse\tValue", 'alternate-reverse'), ("normal\tValue", 'normal'), ("reverse\tValue", 'reverse')],
    'animation-fill-mode': [("backwards\tValue", 'backwards'), ("both\tValue", 'both'), ("forwards\tValue", 'forwards'), ("none\tValue", 'none')],
    'animation-iteration-count': [("infinite\tValue", 'infinite')],
    'animation-name': [("none\tValue", 'none')],
    'animation-play-state': [("paused\tValue", 'paused'), ("running\tValue", 'running')],
    'animation-timing-function': v.timing_function,
    'backface-visibility': [("hidden\tValue", 'hidden'), ("visible\tValue", 'visible')],
    'background': [("auto\tValue", 'auto'), ("border-box\tValue", 'border-box'), ("bottom\tValue", 'bottom'), ("center\tValue", 'center'), ("contain\tValue", 'contain'), ("content-box\tValue", 'content-box'), ("cover\tValue", 'cover'), ("fixed\tValue", 'fixed'), ("left\tValue", 'left'), ("local\tValue", 'local'), ("no-repeat\tValue", 'no-repeat'), ("none\tValue", 'none'), ("padding-box\tValue", 'padding-box'), ("repeat\tValue", 'repeat'), ("repeat-x\tValue", 'repeat-x'), ("repeat-y\tValue", 'repeat-y'), ("right\tValue", 'right'), ("round\tValue", 'round'), ("scroll\tValue", 'scroll'), ("space\tValue", 'space'), ("top\tValue", 'top')] + v.color + v.image,
    'background-attachment': [("fixed\tValue", 'fixed'), ("local\tValue", 'local'), ("scroll\tValue", 'scroll')],
    'background-blend-mode': [("color\tValue", 'color'), ("color-burn\tValue", 'color-burn'), ("color-dodge\tValue", 'color-dodge'), ("darken\tValue", 'darken'), ("difference\tValue", 'difference'), ("exclusion\tValue", 'exclusion'), ("hard-light\tValue", 'hard-light'), ("hue\tValue", 'hue'), ("lighten\tValue", 'lighten'), ("luminosity\tValue", 'luminosity'), ("multiply\tValue", 'multiply'), ("normal\tValue", 'normal'), ("overlay\tValue", 'overlay'), ("saturation\tValue", 'saturation'), ("screen\tValue", 'screen'), ("soft-light\tValue", 'soft-light')],
    'background-clip': [("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("padding-box\tValue", 'padding-box')],
    'background-color': v.color,
    'background-image': [("none\tValue", 'none')] + v.image,
    'background-origin': [("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("padding-box\tValue", 'padding-box')],
    'background-position': v.position,
    'background-repeat': [("no-repeat\tValue", 'no-repeat'), ("repeat\tValue", 'repeat'), ("repeat-x\tValue", 'repeat-x'), ("repeat-y\tValue", 'repeat-y'), ("round\tValue", 'round'), ("space\tValue", 'space')],
    'background-size': [("auto\tValue", 'auto'), ("contain\tValue", 'contain'), ("cover\tValue", 'cover')],
    'baseline-shift': [("baseline\tValue", 'baseline'), ("sub\tValue", 'sub'), ("super\tValue", 'super')],
    'bleed': [("auto\tValue", 'auto')],
    'bookmark-label': [("none\tValue", 'none'), v.attr, v.content, v.counter, v.counters],
    'bookmark-level': [("none\tValue", 'none')],
    'bookmark-state': [("closed\tValue", 'closed'), ("open\tValue", 'open')],
    'border': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("medium\tValue", 'medium'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')] + v.color,
    'border-bottom': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("medium\tValue", 'medium'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')] + v.color,
    'border-bottom-color': v.color,
    'border-bottom-style': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid')],
    'border-bottom-width': [("medium\tValue", 'medium'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')],
    'border-clip': [("normal\tValue", 'normal')],
    'border-clip-bottom': [("normal\tValue", 'normal')],
    'border-clip-left': [("normal\tValue", 'normal')],
    'border-clip-right': [("normal\tValue", 'normal')],
    'border-clip-top': [("normal\tValue", 'normal')],
    'border-collapse': [("collapse\tValue", 'collapse'), ("separate\tValue", 'separate')],
    'border-color': v.color,
    'border-image': [("auto\tValue", 'auto'), ("fill\tValue", 'fill'), ("none\tValue", 'none'), ("repeat\tValue", 'repeat'), ("round\tValue", 'round'), ("space\tValue", 'space'), ("stretch\tValue", 'stretch')] + v.image,
    'border-image-repeat': [("repeat\tValue", 'repeat'), ("round\tValue", 'round'), ("space\tValue", 'space'), ("stretch\tValue", 'stretch')],
    'border-image-slice': [("fill\tValue", 'fill')],
    'border-image-source': [("none\tValue", 'none')] + v.image,
    'border-image-width': [("auto\tValue", 'auto')],
    'border-left': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("medium\tValue", 'medium'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')] + v.color,
    'border-left-color': v.color,
    'border-left-style': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid')],
    'border-left-width': [("medium\tValue", 'medium'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')],
    'border-limit': [("all\tValue", 'all'), ("bottom\tValue", 'bottom'), ("corners\tValue", 'corners'), ("left\tValue", 'left'), ("right\tValue", 'right'), ("sides\tValue", 'sides'), ("top\tValue", 'top')],
    'border-right': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("medium\tValue", 'medium'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')] + v.color,
    'border-right-color': v.color,
    'border-right-style': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid')],
    'border-right-width': [("medium\tValue", 'medium'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')],
    'border-style': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid')],
    'border-top': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("medium\tValue", 'medium'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')] + v.color,
    'border-top-color': v.color,
    'border-top-style': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid')],
    'border-top-width': [("medium\tValue", 'medium'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')],
    'border-width': [("medium\tValue", 'medium'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')],
    'bottom': [("auto\tValue", 'auto')],
    'box-decoration-break': [("clone\tValue", 'clone'), ("slice\tValue", 'slice')],
    'box-shadow': [("inset\tValue", 'inset'), ("none\tValue", 'none')] + v.color,
    'box-sizing': [("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("padding-box\tValue", 'padding-box')],
    'box-snap': [("after\tValue", 'after'), ("before\tValue", 'before'), ("center\tValue", 'center'), ("first-baseline\tValue", 'first-baseline'), ("last-baseline\tValue", 'last-baseline'), ("none\tValue", 'none')],
    'box-suppress': [("discard\tValue", 'discard'), ("hide\tValue", 'hide'), ("show\tValue", 'show')],
    'break-after': [("always\tValue", 'always'), ("any\tValue", 'any'), ("auto\tValue", 'auto'), ("avoid\tValue", 'avoid'), ("avoid-column\tValue", 'avoid-column'), ("avoid-page\tValue", 'avoid-page'), ("avoid-region\tValue", 'avoid-region'), ("column\tValue", 'column'), ("left\tValue", 'left'), ("page\tValue", 'page'), ("recto\tValue", 'recto'), ("region\tValue", 'region'), ("right\tValue", 'right'), ("verso\tValue", 'verso')],
    'break-before': [("always\tValue", 'always'), ("any\tValue", 'any'), ("auto\tValue", 'auto'), ("avoid\tValue", 'avoid'), ("avoid-column\tValue", 'avoid-column'), ("avoid-page\tValue", 'avoid-page'), ("avoid-region\tValue", 'avoid-region'), ("column\tValue", 'column'), ("left\tValue", 'left'), ("page\tValue", 'page'), ("recto\tValue", 'recto'), ("region\tValue", 'region'), ("right\tValue", 'right'), ("verso\tValue", 'verso')],
    'break-inside': [("auto\tValue", 'auto'), ("avoid\tValue", 'avoid'), ("avoid-column\tValue", 'avoid-column'), ("avoid-page\tValue", 'avoid-page'), ("avoid-region\tValue", 'avoid-region')],
    'caption-side': [("after\tValue", 'after'), ("before\tValue", 'before'), ("bottom\tValue", 'bottom'), ("left\tValue", 'left'), ("outside\tValue", 'outside'), ("right\tValue", 'right'), ("top\tValue", 'top')],
    'chains': [("none\tValue", 'none')],
    'child-align': [("auto\tValue", 'auto'), ("bottom\tValue", 'bottom'), ("left\tValue", 'left'), ("middle\tValue", 'middle'), ("right\tValue", 'right'), ("top\tValue", 'top')],
    'clear': [("both\tValue", 'both'), ("left\tValue", 'left'), ("none\tValue", 'none'), ("right\tValue", 'right')],
    'clear-after': [("both\tValue", 'both'), ("bottom\tValue", 'bottom'), ("descendants\tValue", 'descendants'), ("end\tValue", 'end'), ("inside\tValue", 'inside'), ("left\tValue", 'left'), ("none\tValue", 'none'), ("outside\tValue", 'outside'), ("right\tValue", 'right'), ("start\tValue", 'start'), ("top\tValue", 'top')],
    'clear-side': [("auto\tValue", 'auto'), ("both\tValue", 'both')],
    'clip-path': [("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("fill-box\tValue", 'fill-box'), ("margin-box\tValue", 'margin-box'), ("none\tValue", 'none'), ("padding-box\tValue", 'padding-box'), ("stroke-box\tValue", 'stroke-box'), ("view-box\tValue", 'view-box')] + v.basic_shape,
    'clip-rule': [("evenodd\tValue", 'evenodd'), ("nonzero\tValue", 'nonzero')],
    'color': v.color,
    'color-adjust': [("economy\tValue", 'economy'), ("exact\tValue", 'exact')],
    'color-correction': [("auto\tValue", 'auto'), ("sRGB\tValue", 'sRGB')],
    'color-interpolation': [("auto\tValue", 'auto'), ("linearRGB\tValue", 'linearRGB'), ("sRGB\tValue", 'sRGB')],
    'color-interpolation-filters': [("auto\tValue", 'auto'), ("linearRGB\tValue", 'linearRGB'), ("sRGB\tValue", 'sRGB')],
    'column-count': [("auto\tValue", 'auto')],
    'column-fill': [("auto\tValue", 'auto'), ("balance\tValue", 'balance'), ("balance-all\tValue", 'balance-all')],
    'column-gap': [("normal\tValue", 'normal')],
    'column-rule': [("medium\tValue", 'medium'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')] + [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid')] + v.color,
    'column-rule-color': v.color,
    'column-rule-style': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid')],
    'column-rule-width': [("medium\tValue", 'medium'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')],
    'column-span': [("all\tValue", 'all'), ("none\tValue", 'none')],
    'column-width': [("auto\tValue", 'auto')],
    'columns': [("auto\tValue", 'auto')],
    'content': [("close-quote\tValue", 'close-quote'), ("contents\tValue", 'contents'), ("icon\tValue", 'icon'), ("inhibit\tValue", 'inhibit'), ("none\tValue", 'none'), ("normal\tValue", 'normal'), ("no-close-quote\tValue", 'no-close-quote'), ("no-open-quote\tValue", 'no-open-quote'), ("open-quote\tValue", 'open-quote'), v.attr, v.content, v.counter, v.counters, v.url],
    'corner-shape': [("bevel\tValue", 'bevel'), ("notch\tValue", 'notch'), ("round\tValue", 'round'), ("scoop\tValue", 'scoop')],
    'corners': [("bevel\tValue", 'bevel'), ("notch\tValue", 'notch'), ("round\tValue", 'round'), ("scoop\tValue", 'scoop')],
    'counter-increment': [("none\tValue", 'none')],
    'counter-reset': [("none\tValue", 'none')],
    'counter-set': [("none\tValue", 'none')],
    'cue': [("none\tValue", 'none'), v.url],
    'cue-after': [("none\tValue", 'none'), v.url],
    'cue-before': [("none\tValue", 'none'), v.url],
    'cursor': [("alias\tValue", 'alias'), ("all-scroll\tValue", 'all-scroll'), ("auto\tValue", 'auto'), ("cell\tValue", 'cell'), ("col-resize\tValue", 'col-resize'), ("context-menu\tValue", 'context-menu'), ("copy\tValue", 'copy'), ("crosshair\tValue", 'crosshair'), ("default\tValue", 'default'), ("e-resize\tValue", 'e-resize'), ("ew-resize\tValue", 'ew-resize'), ("help\tValue", 'help'), ("move\tValue", 'move'), ("n-resize\tValue", 'n-resize'), ("ne-resize\tValue", 'ne-resize'), ("nesw-resize\tValue", 'nesw-resize'), ("no-drop\tValue", 'no-drop'), ("none\tValue", 'none'), ("not-allowed\tValue", 'not-allowed'), ("ns-resize\tValue", 'ns-resize'), ("nw-resize\tValue", 'nw-resize'), ("nwse-resize\tValue", 'nwse-resize'), ("pointer\tValue", 'pointer'), ("progress\tValue", 'progress'), ("row-resize\tValue", 'row-resize'), ("s-resize\tValue", 's-resize'), ("se-resize\tValue", 'se-resize'), ("sw-resize\tValue", 'sw-resize'), ("text\tValue", 'text'), ("vertical-text\tValue", 'vertical-text'), ("w-resize\tValue", 'w-resize'), ("wait\tValue", 'wait'), ("zoom-in\tValue", 'zoom-in'), ("zoom-out\tValue", 'zoom-out'), v.url],
    'direction': [("ltr\tValue", 'ltr'), ("rtl\tValue", 'rtl')],
    'display': [("auto\tValue", 'auto'), ("block\tValue", 'block'), ("block-level\tValue", 'block-level'), ("contents\tValue", 'contents'), ("flex\tValue", 'flex'), ("grid\tValue", 'grid'), ("inline\tValue", 'inline'), ("inline-block\tValue", 'inline-block'), ("inline-flex\tValue", 'inline-flex'), ("inline-grid\tValue", 'inline-grid'), ("inline-level\tValue", 'inline-level'), ("inline-list-item\tValue", 'inline-list-item'), ("inline-table\tValue", 'inline-table'), ("list-item\tValue", 'list-item'), ("none\tValue", 'none'), ("ruby\tValue", 'ruby'), ("ruby-base\tValue", 'ruby-base'), ("ruby-base-container\tValue", 'ruby-base-container'), ("ruby-text\tValue", 'ruby-text'), ("ruby-text-container\tValue", 'ruby-text-container'), ("run-in\tValue", 'run-in'), ("table\tValue", 'table'), ("table-caption\tValue", 'table-caption'), ("table-cell\tValue", 'table-cell'), ("table-column\tValue", 'table-column'), ("table-column-group\tValue", 'table-column-group'), ("table-footer-group\tValue", 'table-footer-group'), ("table-header-group\tValue", 'table-header-group'), ("table-row\tValue", 'table-row'), ("table-row-group\tValue", 'table-row-group')],
    'display-inside': [("auto\tValue", 'auto'), ("block\tValue", 'block'), ("flex\tValue", 'flex'), ("grid\tValue", 'grid'), ("ruby\tValue", 'ruby'), ("table\tValue", 'table')],
    'display-list': [("list-item\tValue", 'list-item'), ("none\tValue", 'none')],
    'display-outside': [("block-level\tValue", 'block-level'), ("contents\tValue", 'contents'), ("inline-level\tValue", 'inline-level'), ("none\tValue", 'none'), ("ruby-base\tValue", 'ruby-base'), ("ruby-base-container\tValue", 'ruby-base-container'), ("ruby-text\tValue", 'ruby-text'), ("ruby-text-container\tValue", 'ruby-text-container'), ("run-in\tValue", 'run-in'), ("table-caption\tValue", 'table-caption'), ("table-cell\tValue", 'table-cell'), ("table-column\tValue", 'table-column'), ("table-column-group\tValue", 'table-column-group'), ("table-footer-group\tValue", 'table-footer-group'), ("table-header-group\tValue", 'table-header-group'), ("table-row\tValue", 'table-row'), ("table-row-group\tValue", 'table-row-group')],
    'dominant-baseline': [("alphabetic\tValue", 'alphabetic'), ("auto\tValue", 'auto'), ("central\tValue", 'central'), ("hanging\tValue", 'hanging'), ("ideographic\tValue", 'ideographic'), ("mathematical\tValue", 'mathematical'), ("middle\tValue", 'middle'), ("no-change\tValue", 'no-change'), ("reset-size\tValue", 'reset-size'), ("text-over-edge\tValue", 'text-over-edge'), ("text-under-edge\tValue", 'text-under-edge'), ("use-script\tValue", 'use-script')],
    'empty-cells': [("hide\tValue", 'hide'), ("show\tValue", 'show')],
    'fallback': v.counter_style,
    'filter': [("none\tValue", 'none'), v.url] + v.filters,
    'flex': [("auto\tValue", 'auto'), ("content\tValue", 'content'), ("none\tValue", 'none')],
    'flex-basis': [("auto\tValue", 'auto'), ("content\tValue", 'content')],
    'flex-direction': [("column\tValue", 'column'), ("column-reverse\tValue", 'column-reverse'), ("row\tValue", 'row'), ("row-reverse\tValue", 'row-reverse')],
    'flex-flow': [("column\tValue", 'column'), ("column-reverse\tValue", 'column-reverse'), ("nowrap\tValue", 'nowrap'), ("row\tValue", 'row'), ("row-reverse\tValue", 'row-reverse'), ("wrap\tValue", 'wrap'), ("wrap-reverse\tValue", 'wrap-reverse')],
    'flex-wrap': [("nowrap\tValue", 'nowrap'), ("wrap\tValue", 'wrap'), ("wrap-reverse\tValue", 'wrap-reverse')],
    'float': [("bottom\tValue", 'bottom'), ("bottom-corner\tValue", 'bottom-corner'), ("contour\tValue", 'contour'), ("end\tValue", 'end'), ("inside\tValue", 'inside'), ("intrude\tValue", 'intrude'), ("left\tValue", 'left'), ("next-column\tValue", 'next-column'), ("next-page\tValue", 'next-page'), ("none\tValue", 'none'), ("outside\tValue", 'outside'), ("right\tValue", 'right'), ("snap\tValue", 'snap'), ("start\tValue", 'start'), ("top\tValue", 'top'), ("top-corner\tValue", 'top-corner'), ("unless-room\tValue", 'unless-room')],
    'float-defer-column': [("last\tValue", 'last'), ("none\tValue", 'none')],
    'float-defer-page': [("last\tValue", 'last'), ("none\tValue", 'none')],
    'float-displace': [("auto\tValue", 'auto'), ("block\tValue", 'block'), ("block-within-page\tValue", 'block-within-page')],
    'float-wrap': [("none\tValue", 'none'), ("wrap\tValue", 'wrap')],
    'flood-color': v.color + [v.icc_color],
    'flow': [("auto\tValue", 'auto'), ("same\tValue", 'same'), ("*",)],
    'flow-from': [("inherit\tValue", 'inherit'), ("none\tValue", 'none')],
    'flow-into': [("content\tValue", 'content'), ("element\tValue", 'element'), ("none\tValue", 'none')],
    'font': [("100\tValue", '100'), ("200\tValue", '200'), ("300\tValue", '300'), ("400\tValue", '400'), ("500\tValue", '500'), ("600\tValue", '600'), ("700\tValue", '700'), ("800\tValue", '800'), ("900\tValue", '900'), ("bold\tValue", 'bold'), ("bolder\tValue", 'bolder'), ("caption\tValue", 'caption'), ("condensed\tValue", 'condensed'), ("cursive\tValue", 'cursive'), ("expanded\tValue", 'expanded'), ("extra-condensed\tValue", 'extra-condensed'), ("extra-expanded\tValue", 'extra-expanded'), ("fantasy\tValue", 'fantasy'), ("icon\tValue", 'icon'), ("italic\tValue", 'italic'), ("large\tValue", 'large'), ("larger\tValue", 'larger'), ("lighter\tValue", 'lighter'), ("medium\tValue", 'medium'), ("menu\tValue", 'menu'), ("message-box\tValue", 'message-box'), ("monospace\tValue", 'monospace'), ("none\tValue", 'none'), ("normal\tValue", 'normal'), ("oblique\tValue", 'oblique'), ("sans-serif\tValue", 'sans-serif'), ("semi-condensed\tValue", 'semi-condensed'), ("semi-expanded\tValue", 'semi-expanded'), ("serif\tValue", 'serif'), ("small\tValue", 'small'), ("small-caps\tValue", 'small-caps'), ("small-caption\tValue", 'small-caption'), ("smaller\tValue", 'smaller'), ("status-bar\tValue", 'status-bar'), ("ultra-condensed\tValue", 'ultra-condensed'), ("ultra-expanded\tValue", 'ultra-expanded'), ("x-large\tValue", 'x-large'), ("x-small\tValue", 'x-small'), ("xx-large\tValue", 'xx-large'), ("xx-small\tValue", 'xx-small')],
    'font-family': [("cursive\tValue", 'cursive'), ("fantasy\tValue", 'fantasy'), ("monospace\tValue", 'monospace'), ("sans-serif\tValue", 'sans-serif'), ("serif\tValue", 'serif')],
    'font-feature-settings': [("normal\tValue", 'normal'), ("off\tValue", 'off'), ("on\tValue", 'on')],
    'font-kerning': [("auto\tValue", 'auto'), ("none\tValue", 'none'), ("normal\tValue", 'normal')],
    'font-language-override': [("normal\tValue", 'normal')],
    'font-size': [("large\tValue", 'large'), ("larger\tValue", 'larger'), ("medium\tValue", 'medium'), ("small\tValue", 'small'), ("smaller\tValue", 'smaller'), ("x-large\tValue", 'x-large'), ("x-small\tValue", 'x-small'), ("xx-large\tValue", 'xx-large'), ("xx-small\tValue", 'xx-small')],
    'font-size-adjust': [("none\tValue", 'none')],
    'font-stretch': [("condensed\tValue", 'condensed'), ("expanded\tValue", 'expanded'), ("extra-condensed\tValue", 'extra-condensed'), ("extra-expanded\tValue", 'extra-expanded'), ("normal\tValue", 'normal'), ("semi-condensed\tValue", 'semi-condensed'), ("semi-expanded\tValue", 'semi-expanded'), ("ultra-condensed\tValue", 'ultra-condensed'), ("ultra-expanded\tValue", 'ultra-expanded')],
    'font-style': [("italic\tValue", 'italic'), ("normal\tValue", 'normal'), ("oblique\tValue", 'oblique')],
    'font-synthesis': [("none\tValue", 'none'), ("style\tValue", 'style'), ("weight\tValue", 'weight')],
    'font-variant': [("all-petite-caps\tValue", 'all-petite-caps'), ("all-small-caps\tValue", 'all-small-caps'), ("common-ligatures\tValue", 'common-ligatures'), ("contextual\tValue", 'contextual'), ("diagonal-fractions\tValue", 'diagonal-fractions'), ("discretionary-ligatures\tValue", 'discretionary-ligatures'), ("full-width\tValue", 'full-width'), ("historical-forms\tValue", 'historical-forms'), ("historical-ligatures\tValue", 'historical-ligatures'), ('jis04',), ('jis78',), ('jis83',), ('jis90',), ("lining-nums\tValue", 'lining-nums'), ("no-common-ligatures\tValue", 'no-common-ligatures'), ("no-contextual\tValue", 'no-contextual'), ("no-discretionary-ligatures\tValue", 'no-discretionary-ligatures'), ("no-historical-ligatures\tValue", 'no-historical-ligatures'), ("none\tValue", 'none'), ("normal\tValue", 'normal'), ("oldstyle-nums\tValue", 'oldstyle-nums'), ("ordinal\tValue", 'ordinal'), ("petite-caps\tValue", 'petite-caps'), ("proportional-nums\tValue", 'proportional-nums'), ("proportional-width\tValue", 'proportional-width'), ("ruby\tValue", 'ruby'), ("simplified\tValue", 'simplified'), ("slashed-zero\tValue", 'slashed-zero'), ("small-caps\tValue", 'small-caps'), ("stacked-fractions\tValue", 'stacked-fractions'), ("tabular-nums\tValue", 'tabular-nums'), ("titling-caps\tValue", 'titling-caps'), ("traditional\tValue", 'traditional'), ("unicase\tValue", 'unicase'), v.annotation, v.character_variant, v.ornaments, v.styleset, v.stylistic, v.swash],
    'font-variant-alternates': [("historical-forms\tValue", 'historical-forms'), ("normal\tValue", 'normal'), v.annotation, v.character_variant, v.ornaments, v.styleset, v.stylistic, v.swash],
    'font-variant-caps': [("all-petite-caps\tValue", 'all-petite-caps'), ("all-small-caps\tValue", 'all-small-caps'), ("normal\tValue", 'normal'), ("petite-caps\tValue", 'petite-caps'), ("small-caps\tValue", 'small-caps'), ("titling-caps\tValue", 'titling-caps'), ("unicase\tValue", 'unicase')],
    'font-variant-east-asian': [("full-width\tValue", 'full-width'), ('jis04',), ('jis78',), ('jis83',), ('jis90',), ("normal\tValue", 'normal'), ("proportional-width\tValue", 'proportional-width'), ("ruby\tValue", 'ruby'), ("simplified\tValue", 'simplified'), ("traditional\tValue", 'traditional')],
    'font-variant-ligatures': [("common-ligatures\tValue", 'common-ligatures'), ("contextual\tValue", 'contextual'), ("discretionary-ligatures\tValue", 'discretionary-ligatures'), ("historical-ligatures\tValue", 'historical-ligatures'), ("no-common-ligatures\tValue", 'no-common-ligatures'), ("no-contextual\tValue", 'no-contextual'), ("no-discretionary-ligatures\tValue", 'no-discretionary-ligatures'), ("no-historical-ligatures\tValue", 'no-historical-ligatures'), ("none\tValue", 'none'), ("normal\tValue", 'normal')],
    'font-variant-numeric': [("diagonal-fractions\tValue", 'diagonal-fractions'), ("lining-nums\tValue", 'lining-nums'), ("normal\tValue", 'normal'), ("oldstyle-nums\tValue", 'oldstyle-nums'), ("ordinal\tValue", 'ordinal'), ("proportional-nums\tValue", 'proportional-nums'), ("slashed-zero\tValue", 'slashed-zero'), ("stacked-fractions\tValue", 'stacked-fractions'), ("tabular-nums\tValue", 'tabular-nums')],
    'font-variant-position': [("normal\tValue", 'normal'), ("sub\tValue", 'sub'), ("super\tValue", 'super')],
    'font-weight': [("100\tValue", '100'), ("200\tValue", '200'), ("300\tValue", '300'), ("400\tValue", '400'), ("500\tValue", '500'), ("600\tValue", '600'), ("700\tValue", '700'), ("800\tValue", '800'), ("900\tValue", '900'), ("bold\tValue", 'bold'), ("bolder\tValue", 'bolder'), ("lighter\tValue", 'lighter'), ("normal\tValue", 'normal')],
    'footnote-display': [("block\tValue", 'block'), ("compact\tValue", 'compact'), ("inline\tValue", 'inline')],
    'footnote-policy': [("auto\tValue", 'auto'), ("block\tValue", 'block'), ("line\tValue", 'line')],
    'grid': [("auto\tValue", 'auto'), ("column\tValue", 'column'), ("dense\tValue", 'dense'), ("fit-content\tValue", 'fit-content'), ("max-content\tValue", 'max-content'), ("min-content\tValue", 'min-content'), ("none\tValue", 'none'), ("row\tValue", 'row'), ("stack\tValue", 'stack'), ("subgrid\tValue", 'subgrid'), v.minmax, v.repeat],
    'grid-area': [("auto\tValue", 'auto'), ("span\tValue", 'span')],
    'grid-auto-columns': [("auto\tValue", 'auto'), ("max-content\tValue", 'max-content'), ("min-content\tValue", 'min-content'), v.minmax],
    'grid-auto-flow': [("column\tValue", 'column'), ("dense\tValue", 'dense'), ("row\tValue", 'row'), ("stack\tValue", 'stack')],
    'grid-auto-rows': [("auto\tValue", 'auto'), ("max-content\tValue", 'max-content'), ("min-content\tValue", 'min-content'), v.minmax],
    'grid-column': [("auto\tValue", 'auto'), ("span\tValue", 'span')],
    'grid-column-end': [("auto\tValue", 'auto'), ("span\tValue", 'span')],
    'grid-column-start': [("auto\tValue", 'auto'), ("span\tValue", 'span')],
    'grid-row': [("auto\tValue", 'auto'), ("span\tValue", 'span')],
    'grid-row-end': [("auto\tValue", 'auto'), ("span\tValue", 'span')],
    'grid-row-start': [("auto\tValue", 'auto'), ("span\tValue", 'span')],
    'grid-template': [("auto\tValue", 'auto'), ("fit-content\tValue", 'fit-content'), ("max-content\tValue", 'max-content'), ("min-content\tValue", 'min-content'), ("none\tValue", 'none'), ("subgrid\tValue", 'subgrid'), v.minmax, v.repeat],
    'grid-template-areas': [("none\tValue", 'none')],
    'grid-template-columns': [("auto\tValue", 'auto'), ("max-content\tValue", 'max-content'), ("min-content\tValue", 'min-content'), ("none\tValue", 'none'), ("subgrid\tValue", 'subgrid'), v.minmax, v.repeat],
    'grid-template-rows': [("auto\tValue", 'auto'), ("max-content\tValue", 'max-content'), ("min-content\tValue", 'min-content'), ("none\tValue", 'none'), ("subgrid\tValue", 'subgrid'), v.minmax, v.repeat],
    'hanging-punctuation': [("allow-end\tValue", 'allow-end'), ("first\tValue", 'first'), ("force-end\tValue", 'force-end'), ("last\tValue", 'last'), ("none\tValue", 'none')],
    'height': [("auto\tValue", 'auto')],
    'hyphens': [("auto\tValue", 'auto'), ("manual\tValue", 'manual'), ("none\tValue", 'none')],
    'image-resolution': [("from-image\tValue", 'from-image'), ("snap\tValue", 'snap')],
    'indent-edge-reset': [("border-edge\tValue", 'border-edge'), ("content-edge\tValue", 'content-edge'), ("margin-edge\tValue", 'margin-edge'), ("none\tValue", 'none'), ("padding-edge\tValue", 'padding-edge')],
    'initial-letter': [("normal\tValue", 'normal')],
    'initial-letter-align': [("alphabetic\tValue", 'alphabetic'), ("auto\tValue", 'auto'), ("hanging\tValue", 'hanging'), ("ideographic\tValue", 'ideographic')],
    'inline-box-align': [("initial\tValue", 'initial'), ("last\tValue", 'last')],
    'isolation': [("auto\tValue", 'auto'), ("isolate\tValue", 'isolate')],
    'justify-content': [("auto\tValue", 'auto'), ("baseline\tValue", 'baseline'), ("center\tValue", 'center'), ("end\tValue", 'end'), ("flex-end\tValue", 'flex-end'), ("flex-start\tValue", 'flex-start'), ("last-baseline\tValue", 'last-baseline'), ("left\tValue", 'left'), ("right\tValue", 'right'), ("safe\tValue", 'safe'), ("space-around\tValue", 'space-around'), ("space-between\tValue", 'space-between'), ("space-evenly\tValue", 'space-evenly'), ("start\tValue", 'start'), ("stretch\tValue", 'stretch'), ("true\tValue", 'true')],
    'justify-items': [("auto\tValue", 'auto'), ("baseline\tValue", 'baseline'), ("center\tValue", 'center'), ("end\tValue", 'end'), ("flex-end\tValue", 'flex-end'), ("flex-start\tValue", 'flex-start'), ("last-baseline\tValue", 'last-baseline'), ("left\tValue", 'left'), ("legacy\tValue", 'legacy'), ("right\tValue", 'right'), ("safe\tValue", 'safe'), ("self-end\tValue", 'self-end'), ("self-start\tValue", 'self-start'), ("start\tValue", 'start'), ("stretch\tValue", 'stretch'), ("true\tValue", 'true')],
    'justify-self':  [("auto\tValue", 'auto'), ("baseline\tValue", 'baseline'), ("center\tValue", 'center'), ("end\tValue", 'end'), ("flex-end\tValue", 'flex-end'), ("flex-start\tValue", 'flex-start'), ("last-baseline\tValue", 'last-baseline'), ("left\tValue", 'left'), ("right\tValue", 'right'), ("safe\tValue", 'safe'), ("self-end\tValue", 'self-end'), ("self-start\tValue", 'self-start'), ("start\tValue", 'start'), ("stretch\tValue", 'stretch'), ("true\tValue", 'true')],
    'left': [("auto\tValue", 'auto')],
    'letter-spacing': [('normal')],
    'lighting-color': v.color + [v.icc_color],
    'line-break': [("auto\tValue", 'auto'), ("loose\tValue", 'loose'), ("normal\tValue", 'normal'), ("strict\tValue", 'strict')],
    'line-grid': [("create\tValue", 'create'), ("match-parent\tValue", 'match-parent')],
    'line-height': [("none\tValue", 'none'), ("normal\tValue", 'normal')],
    'line-snap': [("baseline\tValue", 'baseline'), ("contain\tValue", 'contain'), ("none\tValue", 'none')],
    'line-stacking': [("block-line-height\tValue", 'block-line-height'), ("consider-shifts\tValue", 'consider-shifts'), ("disregard-shifts\tValue", 'disregard-shifts'), ("exclude-ruby\tValue", 'exclude-ruby'), ("grid-height\tValue", 'grid-height'), ("include-ruby\tValue", 'include-ruby'), ("inline-line-height\tValue", 'inline-line-height'), ("max-height\tValue", 'max-height')],
    'line-stacking-ruby': [("exclude-ruby\tValue", 'exclude-ruby'), ("include-ruby\tValue", 'include-ruby')],
    'line-stacking-shift': [("consider-shifts\tValue", 'consider-shifts'), ("disregard-shifts\tValue", 'disregard-shifts')],
    'line-stacking-strategy': [("block-line-height\tValue", 'block-line-height'), ("grid-height\tValue", 'grid-height'), ("inline-line-height\tValue", 'inline-line-height'), ("max-height\tValue", 'max-height')],
    'list-style': [("inside\tValue", 'inside'), ("none\tValue", 'none'), ("outside\tValue", 'outside'), v.symbols] + v.image + v.counter_style,
    'list-style-image': [("none\tValue", 'none')] + v.image,
    'list-style-position': [("inside\tValue", 'inside'), ("outside\tValue", 'outside')],
    'list-style-type': [("none\tValue", 'none'), v.symbols] + v.counter_style,
    'margin': [("auto\tValue", 'auto'), ("fill\tValue", 'fill')],
    'margin-bottom': [("auto\tValue", 'auto'), ("fill\tValue", 'fill')],
    'margin-left': [("auto\tValue", 'auto'), ("fill\tValue", 'fill')],
    'margin-right': [("auto\tValue", 'auto'), ("fill\tValue", 'fill')],
    'margin-top': [("auto\tValue", 'auto'), ("fill\tValue", 'fill')],
    'marker-side': [("list-container\tValue", 'list-container'), ("list-item\tValue", 'list-item')],
    'marks': [("crop\tValue", 'crop'), ("cross\tValue", 'cross'), ("none\tValue", 'none')],
    'mask': [("add\tValue", 'add'), ("alpha\tValue", 'alpha'), ("auto\tValue", 'auto'), ("border-box\tValue", 'border-box'), ("contain\tValue", 'contain'), ("content-box\tValue", 'content-box'), ("cover\tValue", 'cover'), ("exclude\tValue", 'exclude'), ("fill-box\tValue", 'fill-box'), ("intersect\tValue", 'intersect'), ("luminance\tValue", 'luminance'), ("margin-box\tValue", 'margin-box'), ("no-clip\tValue", 'no-clip'), ("no-repeat\tValue", 'no-repeat'), ("none\tValue", 'none'), ("padding-box\tValue", 'padding-box'), ("repeat\tValue", 'repeat'), ("repeat-x\tValue", 'repeat-x'), ("repeat-y\tValue", 'repeat-y'), ("round\tValue", 'round'), ("space\tValue", 'space'), ("stroke-box\tValue", 'stroke-box'), ("subtract\tValue", 'subtract'), ("view-box\tValue", 'view-box'), v.url] + v.position + v.image,
    'mask-border': [("alpha\tValue", 'alpha'), ("auto\tValue", 'auto'), ("fill\tValue", 'fill'), ("luminance\tValue", 'luminance'), ("none\tValue", 'none'), ("repeat\tValue", 'repeat'), ("round\tValue", 'round'), ("space\tValue", 'space'), ("stretch\tValue", 'stretch')] + v.image,
    'mask-border-mode': [("alpha\tValue", 'alpha'), ("luminance\tValue", 'luminance')],
    'mask-border-repeat': [("repeat\tValue", 'repeat'), ("round\tValue", 'round'), ("space\tValue", 'space'), ("stretch\tValue", 'stretch')],
    'mask-border-slice': [("fill\tValue", 'fill')],
    'mask-border-source': [("none\tValue", 'none')] + v.image,
    'mask-border-width': [("auto\tValue", 'auto')],
    'mask-clip': [("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("fill-box\tValue", 'fill-box'), ("margin-box\tValue", 'margin-box'), ("no-clip\tValue", 'no-clip'), ("padding-box\tValue", 'padding-box'), ("stroke-box\tValue", 'stroke-box'), ("view-box\tValue", 'view-box')],
    'mask-composite': [("add\tValue", 'add'), ("exclude\tValue", 'exclude'), ("intersect\tValue", 'intersect'), ("subtract\tValue", 'subtract')],
    'mask-image': [("none\tValue", 'none'), v.url] + v.image,
    'mask-mode': [("alpha\tValue", 'alpha'), ("auto\tValue", 'auto'), ("luminance\tValue", 'luminance')],
    'mask-origin': [("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("fill-box\tValue", 'fill-box'), ("margin-box\tValue", 'margin-box'), ("padding-box\tValue", 'padding-box'), ("stroke-box\tValue", 'stroke-box'), ("view-box\tValue", 'view-box')],
    'mask-position': v.position,
    'mask-repeat': [("no-repeat\tValue", 'no-repeat'), ("repeat\tValue", 'repeat'), ("repeat-x\tValue", 'repeat-x'), ("repeat-y\tValue", 'repeat-y'), ("round\tValue", 'round'), ("space\tValue", 'space')],
    'mask-size': [("auto\tValue", 'auto'), ("contain\tValue", 'contain'), ("cover\tValue", 'cover')],
    'mask-type': [("alpha\tValue", 'alpha'), ("luminance\tValue", 'luminance')],
    'max-height': [("available\tValue", 'available'), ("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("extend-to-zoom\tValue", 'extend-to-zoom'), ("fit-content\tValue", 'fit-content'), ("max-content\tValue", 'max-content'), ("min-content\tValue", 'min-content'), ("none\tValue", 'none')],
    'max-lines': [("none\tValue", 'none')],
    'max-width': [("available\tValue", 'available'), ("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("extend-to-zoom\tValue", 'extend-to-zoom'), ("fit-content\tValue", 'fit-content'), ("max-content\tValue", 'max-content'), ("min-content\tValue", 'min-content'), ("none\tValue", 'none')],
    'max-zoom': [("auto\tValue", 'auto')],
    'min-height': [("available\tValue", 'available'), ("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("extend-to-zoom\tValue", 'extend-to-zoom'), ("fit-content\tValue", 'fit-content'), ("max-content\tValue", 'max-content'), ("min-content\tValue", 'min-content')],
    'min-width': [("available\tValue", 'available'), ("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("extend-to-zoom\tValue", 'extend-to-zoom'), ("fit-content\tValue", 'fit-content'), ("max-content\tValue", 'max-content'), ("min-content\tValue", 'min-content')],
    'min-zoom': [("auto\tValue", 'auto')],
    'mix-blend-mode': [("color\tValue", 'color'), ("color-burn\tValue", 'color-burn'), ("color-dodge\tValue", 'color-dodge'), ("darken\tValue", 'darken'), ("difference\tValue", 'difference'), ("exclusion\tValue", 'exclusion'), ("hard-light\tValue", 'hard-light'), ("hue\tValue", 'hue'), ("lighten\tValue", 'lighten'), ("luminosity\tValue", 'luminosity'), ("multiply\tValue", 'multiply'), ("normal\tValue", 'normal'), ("overlay\tValue", 'overlay'), ("saturation\tValue", 'saturation'), ("screen\tValue", 'screen'), ("soft-light\tValue", 'soft-light')],
    'motion': [("auto\tValue", 'auto'), ("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("fill-box\tValue", 'fill-box'), ("margin-box\tValue", 'margin-box'), ("none\tValue", 'none'), ("padding-box\tValue", 'padding-box'), ("reverse\tValue", 'reverse'), ("stroke-box\tValue", 'stroke-box'), ("view-box\tValue", 'view-box'), v.circle, v.ellipse, v.inset, v.path, v.polygon, v.url],
    'motion-path': [("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("fill-box\tValue", 'fill-box'), ("margin-box\tValue", 'margin-box'), ("none\tValue", 'none'), ("padding-box\tValue", 'padding-box'), ("stroke-box\tValue", 'stroke-box'), ("view-box\tValue", 'view-box'), v.circle, v.ellipse, v.inset, v.path, v.polygon, v.url],
    'motion-rotation': [("auto\tValue", 'auto'), ("reverse\tValue", 'reverse')],
    'nav-down': [("auto\tValue", 'auto'), ("current\tValue", 'current'), ("root\tValue", 'root')],
    'nav-left': [("auto\tValue", 'auto'), ("current\tValue", 'current'), ("root\tValue", 'root')],
    'nav-right': [("auto\tValue", 'auto'), ("current\tValue", 'current'), ("root\tValue", 'root')],
    'nav-up': [("auto\tValue", 'auto'), ("current\tValue", 'current'), ("root\tValue", 'root')],
    'negative': v.image,
    'object-fit': [("contain\tValue", 'contain'), ("cover\tValue", 'cover'), ("fill\tValue", 'fill'), ("none\tValue", 'none'), ("scale-down\tValue", 'scale-down')],
    'object-position': v.position,
    'offset-after': [("auto\tValue", 'auto')],
    'offset-before': [("auto\tValue", 'auto')],
    'offset-end': [("auto\tValue", 'auto')],
    'offset-start': [("auto\tValue", 'auto')],
    'orientation': [("auto\tValue", 'auto'), ("landscape\tValue", 'landscape'), ("portrait\tValue", 'portrait')],
    'outline': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("invert\tValue", 'invert'), ("medium\tValue", 'medium'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')] + v.color,
    'outline-color': [("invert\tValue", 'invert')] + v.color,
    'outline-style': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("groove\tValue", 'groove'), ("hidden\tValue", 'hidden'), ("inset\tValue", 'inset'), ("none\tValue", 'none'), ("outset\tValue", 'outset'), ("ridge\tValue", 'ridge'), ("solid\tValue", 'solid')],
    'outline-width': [("medium\tValue", 'medium'), ("thick\tValue", 'thick'), ("thin\tValue", 'thin')],
    'overflow': [("auto\tValue", 'auto'), ("fragments\tValue", 'fragments'), ("hidden\tValue", 'hidden'), ("paged-x\tValue", 'paged-x'), ("paged-x-controls\tValue", 'paged-x-controls'), ("paged-y\tValue", 'paged-y'), ("paged-y-controls\tValue", 'paged-y-controls'), ("scroll\tValue", 'scroll'), ("visible\tValue", 'visible')],
    'overflow-wrap': [("break-word\tValue", 'break-word'), ("normal\tValue", 'normal')],
    'overflow-x': [("auto\tValue", 'auto'), ("fragments\tValue", 'fragments'), ("hidden\tValue", 'hidden'), ("paged-x\tValue", 'paged-x'), ("paged-x-controls\tValue", 'paged-x-controls'), ("paged-y\tValue", 'paged-y'), ("paged-y-controls\tValue", 'paged-y-controls'), ("scroll\tValue", 'scroll'), ("visible\tValue", 'visible')],
    'overflow-y': [("auto\tValue", 'auto'), ("fragments\tValue", 'fragments'), ("hidden\tValue", 'hidden'), ("paged-x\tValue", 'paged-x'), ("paged-x-controls\tValue", 'paged-x-controls'), ("paged-y\tValue", 'paged-y'), ("paged-y-controls\tValue", 'paged-y-controls'), ("scroll\tValue", 'scroll'), ("visible\tValue", 'visible')],
    'pad': v.image,
    'page': [("auto\tValue", 'auto')],
    'page-policy': [("first\tValue", 'first'), ("last\tValue", 'last'), ("start\tValue", 'start')],
    'pause': [("medium\tValue", 'medium'), ("none\tValue", 'none'), ("strong\tValue", 'strong'), ("weak\tValue", 'weak'), ("x-strong\tValue", 'x-strong'), ("x-weak\tValue", 'x-weak')],
    'pause-after': [("medium\tValue", 'medium'), ("none\tValue", 'none'), ("strong\tValue", 'strong'), ("weak\tValue", 'weak'), ("x-strong\tValue", 'x-strong'), ("x-weak\tValue", 'x-weak')],
    'pause-before': [("medium\tValue", 'medium'), ("none\tValue", 'none'), ("strong\tValue", 'strong'), ("weak\tValue", 'weak'), ("x-strong\tValue", 'x-strong'), ("x-weak\tValue", 'x-weak')],
    'perspective': [("none\tValue", 'none')],
    'perspective-origin': v.position,
    'pointer-events': [("all\tValue", 'all'), ("auto\tValue", 'auto'), ("fill\tValue", 'fill'), ("none\tValue", 'none'), ("painted\tValue", 'painted'), ("stroke\tValue", 'stroke'), ("visible\tValue", 'visible'), ("visibleFill\tValue", 'visibleFill'), ("visiblePainted\tValue", 'visiblePainted'), ("visibleStroke\tValue", 'visibleStroke')],
    'position': [("absolute\tValue", 'absolute'), ("center\tValue", 'center'), ("fixed\tValue", 'fixed'), ("page\tValue", 'page'), ("relative\tValue", 'relative'), ("static\tValue", 'static'), ("sticky\tValue", 'sticky')],
    'prefix': v.image,
    'quotes': [("none\tValue", 'none')],
    'range': [("auto\tValue", 'auto'), ("infinite\tValue", 'infinite')],
    'region-fragment': [("auto\tValue", 'auto'), ("break\tValue", 'break')],
    'resize': [("both\tValue", 'both'), ("horizontal\tValue", 'horizontal'), ("inherit\tValue", 'inherit'), ("none\tValue", 'none'), ("vertical\tValue", 'vertical')],
    'resolution': [("auto\tValue", 'auto'), ("device\tValue", 'device')],
    'rest': [("medium\tValue", 'medium'), ("none\tValue", 'none'), ("strong\tValue", 'strong'), ("weak\tValue", 'weak'), ("x-strong\tValue", 'x-strong'), ("x-weak\tValue", 'x-weak')],
    'rest-after': [("medium\tValue", 'medium'), ("none\tValue", 'none'), ("strong\tValue", 'strong'), ("weak\tValue", 'weak'), ("x-strong\tValue", 'x-strong'), ("x-weak\tValue", 'x-weak')],
    'rest-before': [("medium\tValue", 'medium'), ("none\tValue", 'none'), ("strong\tValue", 'strong'), ("weak\tValue", 'weak'), ("x-strong\tValue", 'x-strong'), ("x-weak\tValue", 'x-weak')],
    'right': [("auto\tValue", 'auto')],
    'rotation-point': v.position,
    'ruby-align': [("center\tValue", 'center'), ("space-around\tValue", 'space-around'), ("space-between\tValue", 'space-between'), ("start\tValue", 'start')],
    'ruby-merge': [("auto\tValue", 'auto'), ("collapse\tValue", 'collapse'), ("separate\tValue", 'separate')],
    'ruby-position': [("inter-character\tValue", 'inter-character'), ("left\tValue", 'left'), ("over\tValue", 'over'), ("right\tValue", 'right'), ("under\tValue", 'under')],
    'scroll-snap-coordinate': [("none\tValue", 'none'), v.position],
    'scroll-snap-destination': v.position,
    'scroll-snap-points-x': [("none\tValue", 'none'), v.repeat],
    'scroll-snap-points-y': [("none\tValue", 'none'), v.repeat],
    'scroll-snap-type': [("mandatory\tValue", 'mandatory'), ("none\tValue", 'none'), ("proximity\tValue", 'proximity')],
    'shape-outside': [("border-box\tValue", 'border-box'), ("content-box\tValue", 'content-box'), ("margin-box\tValue", 'margin-box'), ("none\tValue", 'none'), ("padding-box\tValue", 'padding-box'), v.circle, v.ellipse, v.inset, v.polygon] + v.image,
    'size': [('A3',), ('A4',), ('A5',), ('B4',), ('B5',), ("auto\tValue", 'auto'), ("landscape\tValue", 'landscape'), ("ledger\tValue", 'ledger'), ("legal\tValue", 'legal'), ("letter\tValue", 'letter'), ("portrait\tValue", 'portrait')],
    'speak': [("auto\tValue", 'auto'), ("none\tValue", 'none'), ("normal\tValue", 'normal')],
    # there is also a speak-as descriptor for @counter-style. the values here are a mix of the two properties.
    'speak-as': [("auto\tValue", 'auto'), ("bullets\tValue", 'bullets'), ("digits\tValue", 'digits'), ("literal-punctuation\tValue", 'literal-punctuation'), ("no-punctuation\tValue", 'no-punctuation'), ("normal\tValue", 'normal'), ("numbers\tValue", 'numbers'), ("spell-out\tValue", 'spell-out'), ("words\tValue", 'words')],
    'src': [v.format_func, v.local, v.url],
    'string-set': [("none\tValue", 'none'), v.content, v.counter, v.counters],
    'suffix': v.image,
    'symbols': v.image,
    'system': [("additive\tValue", 'additive'), ("alphabetic\tValue", 'alphabetic'), ("cyclic\tValue", 'cyclic'), ("extends\tValue", 'extends'), ("fixed\tValue", 'fixed'), ("numeric\tValue", 'numeric'), ("symbolic\tValue", 'symbolic')] + v.counter_style,
    'table-layout': [("auto\tValue", 'auto'), ("fixed\tValue", 'fixed')],
    'text-align': [("center\tValue", 'center'), ("end\tValue", 'end'), ("justify\tValue", 'justify'), ("justify-all\tValue", 'justify-all'), ("left\tValue", 'left'), ("match-parent\tValue", 'match-parent'), ("right\tValue", 'right'), ("start\tValue", 'start')],
    'text-align-last': [("auto\tValue", 'auto'), ("center\tValue", 'center'), ("end\tValue", 'end'), ("justify\tValue", 'justify'), ("left\tValue", 'left'), ("right\tValue", 'right'), ("start\tValue", 'start')],
    'text-combine-upright': [("all\tValue", 'all'), ("digits\tValue", 'digits'), ("none\tValue", 'none')],
    'text-decoration': [("blink\tValue", 'blink'), ("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("line-through\tValue", 'line-through'), ("none\tValue", 'none'), ("overline\tValue", 'overline'), ("solid\tValue", 'solid'), ("underline\tValue", 'underline'), ("wavy\tValue", 'wavy')] + v.color,
    'text-decoration-color': v.color,
    'text-decoration-line': [("blink\tValue", 'blink'), ("line-through\tValue", 'line-through'), ("none\tValue", 'none'), ("overline\tValue", 'overline'), ("underline\tValue", 'underline')],
    'text-decoration-skip': [("box-decoration\tValue", 'box-decoration'), ("edges\tValue", 'edges'), ("ink\tValue", 'ink'), ("none\tValue", 'none'), ("objects\tValue", 'objects'), ("spaces\tValue", 'spaces')],
    'text-decoration-style': [("dashed\tValue", 'dashed'), ("dotted\tValue", 'dotted'), ("double\tValue", 'double'), ("solid\tValue", 'solid'), ("wavy\tValue", 'wavy')],
    'text-emphasis': [("circle\tValue", 'circle'), ("dot\tValue", 'dot'), ("double-circle\tValue", 'double-circle'), ("filled\tValue", 'filled'), ("none\tValue", 'none'), ("open\tValue", 'open'), ("sesame\tValue", 'sesame'), ("triangle\tValue", 'triangle')] + v.color,
    'text-emphasis-color': v.color,
    'text-emphasis-position': [("left\tValue", 'left'), ("over\tValue", 'over'), ("right\tValue", 'right'), ("under\tValue", 'under')],
    'text-emphasis-style': [("circle\tValue", 'circle'), ("dot\tValue", 'dot'), ("double-circle\tValue", 'double-circle'), ("filled\tValue", 'filled'), ("none\tValue", 'none'), ("open\tValue", 'open'), ("sesame\tValue", 'sesame'), ("triangle\tValue", 'triangle')],
    'text-height': [("auto\tValue", 'auto'), ("font-size\tValue", 'font-size'), ("max-size\tValue", 'max-size'), ("text-size\tValue", 'text-size')],
    'text-indent': [("each-line\tValue", 'each-line'), ("hanging\tValue", 'hanging')],
    'text-justify': [("auto\tValue", 'auto'), ("distribute\tValue", 'distribute'), ("inter-word\tValue", 'inter-word'), ("none\tValue", 'none')],
    'text-orientation': [("mixed\tValue", 'mixed'), ("sideways\tValue", 'sideways'), ("sideways-left\tValue", 'sideways-left'), ("sideways-right\tValue", 'sideways-right'), ("upright\tValue", 'upright'), ("use-glyph-orientation\tValue", 'use-glyph-orientation')],
    'text-overflow': [("clip\tValue", 'clip'), ("ellipsis\tValue", 'ellipsis')],
    'text-shadow': [("none\tValue", 'none')] + v.color,
    'text-transform': [("capitalize\tValue", 'capitalize'), ("full-width\tValue", 'full-width'), ("lowercase\tValue", 'lowercase'), ("none\tValue", 'none'), ("uppercase\tValue", 'uppercase')],
    'text-underline-position': [("auto\tValue", 'auto'), ("left\tValue", 'left'), ("right\tValue", 'right'), ("under\tValue", 'under')],
    'top': [("auto\tValue", 'auto')],
    'transform': [("none\tValue", 'none')] + v.transform,
    'transform-box': [("border-box\tValue", 'border-box'), ("fill-box\tValue", 'fill-box'), ("view-box\tValue", 'view-box')],
    'transform-origin': v.position,
    'transform-style': [("flat\tValue", 'flat'), ("preserve-3d\tValue",'preserve-3d')],
    'transition': [("all\tValue", 'all'), ("background\tValue", 'background'), ("background-color\tValue", 'background-color'), ("background-image\tValue", 'background-image'), ("background-position\tValue", 'background-position'), ("background-size\tValue", 'background-size'), ("border\tValue", 'border'), ("border-bottom\tValue", 'border-bottom'), ("border-bottom-color\tValue", 'border-bottom-color'), ("border-bottom-left-radius\tValue", 'border-bottom-left-radius'), ("border-bottom-right-radius\tValue", 'border-bottom-right-radius'), ("border-bottom-width\tValue", 'border-bottom-width'), ("border-color\tValue", 'border-color'), ("border-left\tValue", 'border-left'), ("border-left-color\tValue", 'border-left-color'), ("border-left-width\tValue", 'border-left-width'), ("border-radius\tValue", 'border-radius'), ("border-right\tValue", 'border-right'), ("border-right-color\tValue", 'border-right-color'), ("border-right-width\tValue", 'border-right-width'), ("border-top\tValue", 'border-top'), ("border-top-color\tValue", 'border-top-color'), ("border-top-left-radius\tValue", 'border-top-left-radius'), ("border-top-right-radius\tValue", 'border-top-right-radius'), ("border-top-width\tValue", 'border-top-width'), ("border-width\tValue", 'border-width'), ("bottom\tValue", 'bottom'), ("box-shadow\tValue", 'box-shadow'), ("clip\tValue", 'clip'), ("color\tValue", 'color'), ("column-count\tValue", 'column-count'), ("column-gap\tValue", 'column-gap'), ("column-rule\tValue", 'column-rule'), ("column-rule-color\tValue", 'column-rule-color'), ("column-rule-width\tValue", 'column-rule-width'), ("column-width\tValue", 'column-width'), ("columns\tValue", 'columns'), ("flex\tValue", 'flex'), ("flex-basis\tValue", 'flex-basis'), ("flex-grow\tValue", 'flex-grow'), ("flex-shrink\tValue", 'flex-shrink'), ("font\tValue", 'font'), ("font-size\tValue", 'font-size'), ("font-size-adjust\tValue", 'font-size-adjust'), ("font-stretch\tValue", 'font-stretch'), ("font-weight\tValue", 'font-weight'), ("height\tValue", 'height'), ("left\tValue", 'left'), ("letter-spacing\tValue", 'letter-spacing'), ("line-height\tValue", 'line-height'), ("margin\tValue", 'margin'), ("margin-bottom\tValue", 'margin-bottom'), ("margin-left\tValue", 'margin-left'), ("margin-right\tValue", 'margin-right'), ("margin-top\tValue", 'margin-top'), ("max-height\tValue", 'max-height'), ("max-width\tValue", 'max-width'), ("min-height\tValue", 'min-height'), ("min-width\tValue", 'min-width'), ("none\tValue", 'none'), ("opacity\tValue", 'opacity'), ("order\tValue", 'order'), ("outline\tValue", 'outline'), ("outline-color\tValue", 'outline-color'), ("outline-offset\tValue", 'outline-offset'), ("outline-width\tValue", 'outline-width'), ("padding\tValue", 'padding'), ("padding-bottom\tValue", 'padding-bottom'), ("padding-left\tValue", 'padding-left'), ("padding-right\tValue", 'padding-right'), ("padding-top\tValue", 'padding-top'), ("perspective\tValue", 'perspective'), ("perspective-origin\tValue", 'perspective-origin'), ("right\tValue", 'right'), ("shape-image-threshold\tValue", 'shape-image-threshold'), ("shape-margin\tValue", 'shape-margin'), ("shape-outside\tValue", 'shape-outside'), ("text-decoration\tValue", 'text-decoration'), ("text-decoration-color\tValue", 'text-decoration-color'), ("text-indent\tValue", 'text-indent'), ("text-shadow\tValue", 'text-shadow'), ("top\tValue", 'top'), ("transform\tValue", 'transform'), ("transform-origin\tValue", 'transform-origin'), ("vertical-align\tValue", 'vertical-align'), ("visibility\tValue", 'visibility'), ("width\tValue", 'width'), ("word-spacing\tValue", 'word-spacing'), ("z-index\tValue", 'z-index')] + v.timing_function,
    'transition-property': [("all\tValue", 'all'), ("none\tValue", 'none')],
    'transition-timing-function': v.timing_function,
    'unicode-bidi': [("bidi-override\tValue", 'bidi-override'), ("embed\tValue", 'embed'), ("isolate\tValue", 'isolate'), ("isolate-override\tValue", 'isolate-override'), ("normal\tValue", 'normal'), ("plaintext\tValue", 'plaintext')],
    'user-zoom': [("fixed\tValue", 'fixed'), ("zoom\tValue", 'zoom')],
    'vertical-align': [("auto\tValue", 'auto'), ("baseline\tValue", 'baseline'), ("bottom\tValue", 'bottom'), ("central\tValue", 'central'), ("middle\tValue", 'middle'), ("sub\tValue", 'sub'), ("super\tValue", 'super'), ("text-bottom\tValue", 'text-bottom'), ("text-top\tValue", 'text-top'), ("top\tValue", 'top')],
    'visibility': [("collapse\tValue", 'collapse'), ("hidden\tValue", 'hidden'), ("visible\tValue", 'visible')],
    'voice-balance': [("center\tValue", 'center'), ("left\tValue", 'left'), ("leftwards\tValue", 'leftwards'), ("right\tValue", 'right'), ("rightwards\tValue", 'rightwards')],
    'voice-duration': [("auto\tValue", 'auto')],
    'voice-family': [("child\tValue", 'child'), ("female\tValue", 'female'), ("male\tValue", 'male'), ("neutral\tValue", 'neutral'), ("old\tValue", 'old'), ("preserve\tValue", 'preserve'), ("young\tValue", 'young')],
    'voice-pitch': [("absolute\tValue", 'absolute'), ("high\tValue", 'high'), ("low\tValue", 'low'), ("medium\tValue", 'medium'), ("x-high\tValue", 'x-high'), ("x-low\tValue", 'x-low')],
    'voice-range': [("absolute\tValue", 'absolute'), ("high\tValue", 'high'), ("low\tValue", 'low'), ("medium\tValue", 'medium'), ("x-high\tValue", 'x-high'), ("x-low\tValue", 'x-low')],
    'voice-rate': [("fast\tValue", 'fast'), ("medium\tValue", 'medium'), ("normal\tValue", 'normal'), ("slow\tValue", 'slow'), ("x-fast\tValue", 'x-fast'), ("x-slow\tValue", 'x-slow')],
    'voice-stress': [("moderate\tValue", 'moderate'), ("none\tValue", 'none'), ("normal\tValue", 'normal'), ("reduced\tValue", 'reduced'), ("strong\tValue", 'strong')],
    'voice-volume': [("loud\tValue", 'loud'), ("medium\tValue", 'medium'), ("silent\tValue", 'silent'), ("soft\tValue", 'soft'), ("x-loud\tValue", 'x-loud'), ("x-soft\tValue", 'x-soft')],
    'white-space': [("normal\tValue", 'normal'), ("nowrap\tValue", 'nowrap'), ("pre\tValue", 'pre'), ("pre-line\tValue", 'pre-line'), ("pre-wrap\tValue", 'pre-wrap')],
    'width': [("auto\tValue", 'auto')],
    'will-change': [("auto\tValue", 'auto'), ("contents\tValue", 'contents'), ("scroll-position\tValue", 'scroll-position')],
    'word-break': [("break-all\tValue", 'break-all'), ("keep-all\tValue", 'keep-all'), ("normal\tValue", 'normal')],
    'word-spacing': [("normal\tValue", 'normal')],
    'word-wrap': [("break-word\tValue", 'break-word'), ("normal\tValue", 'normal')],
    'wrap-flow': [("auto\tValue", 'auto'), ("both\tValue", 'both'), ("clear\tValue", 'clear'), ("end\tValue", 'end'), ("maximum\tValue", 'maximum'), ("minimum\tValue", 'minimum'), ("start\tValue", 'start')],
    'wrap-through': [("none\tValue", 'none'), ("wrap\tValue", 'wrap')],
    'writing-mode': [("horizontal-tb\tValue", 'horizontal-tb'), ("vertical-lr\tValue", 'vertical-lr'), ("vertical-rl\tValue", 'vertical-rl')],
    'z-index': [("auto\tValue", 'auto')],
    'zoom': [("auto\tValue", 'auto')],

    'fill': v.color + [("none\tValue", 'none')],
    'fill-rule': [("evenodd\tSVG", 'evenodd'), ("nonzero\tSVG", 'nonzero')],
    'stroke': v.color + [("none\tValue", 'none')],
    'stroke-linecap': [("butt\tSVG",'butt'), ("round\tSVG", 'round'), ("square\tSVG", 'square')],
    'stroke-linejoin': [("miter\tSVG", 'miter'), ("round\tSVG", 'round'), ("bevel\tSVG", 'bevel')],

    'flex-direction': [("row\tValue", "row"), ("row-reverse\tValue", "row-reverse"), ("column\tValue", "column"), ("column-reverse\tValue", "column-reverse")],
    'flex-wrap': [("nowrap\tValue", "nowrap"), ("wrap\tValue", "wrap"), ("wrap-reverse\tValue", "wrap-reverse")],
    'flex-flow': [("row\tValue", "row"), ("row-reverse\tValue", "row-reverse"), ("column\tValue", "column"), ("column-reverse\tValue", "column-reverse"), ("nowrap\tValue", "nowrap"), ("wrap\tValue", "wrap"), ("wrap-reverse\tValue", "wrap-reverse")],
    'align-items': [("flex-start\tValue", "flex-start"), ("flex-end\tValue", "flex-end"), ("center\tValue", "center"), ("baseline\tValue", "baseline"), ("stretch\tValue", "stretch")],
    'align-self': [("flex-start\tValue", "flex-start"), ("flex-end\tValue", "flex-end"), ("center\tValue", "center"), ("baseline\tValue", "baseline"), ("stretch\tValue", "stretch")],
    'align-content': [("flex-start\tValue", "flex-start"), ("flex-end\tValue", "flex-end"), ("center\tValue", "center"), ("space-between\tValue", "space-between"), ("space-around\tValue", "space-around"), ("stretch\tValue", "stretch")],
}

# CSS Defualt Value
default_value = [

    # sass function
    ("length\tFunction", "length($1)"),
    ("nth\tFunction", "nth($1)"),
    ("join\tFunction", "join($1)"),
    ("append\tFunction", "append($1)"),
    ("zip\tFunction", "zip($1)"),
    ("index\tFunction", "index($1)"),
    ("list-separator\tFunction", "list-separator($1)"),
    ("map-get\tFunction", "map-get($1)"),
    ("map-merge\tFunction", "map-merge($1)"),
    ("map-keys\tFunction", "map-keys($1)"),
    ("map-values\tFunction", "map-values($1)"),
    ("map-remove\tFunction", "map-remove($1)"),
    ("map-has-key\tFunction", "map-has-key($1)"),
    ("keywords\tFunction", "keywords($1)"),
    ("unquote\tFunction", "unquote($1)"),
    ("quote\tFunction", "quote($1)"),
    ("str-length\tFunction", "str-length($1)"),
    ("str-insert\tFunction", "str-insert($1)"),
    ("str-index\tFunction", "str-index($1)"),
    ("str-slice\tFunction", "str-slice($1)"),
    ("To-upper-case\tFunction", "To-upper-case($1)"),
    ("To-lower-case\tFunction", "To-lower-case($1)"),
    ("percentage\tFunction", "percentage($1)"),
    ("round\tFunction", "round($1)"),
    ("ceil\tFunction", "ceil($1)"),
    ("floor\tFunction", "floor($1)"),
    ("abs\tFunction", "abs($1)"),
    ("min\tFunction", "min($1)"),
    ("max\tFunction", "max($1)"),
    ("random\tFunction", "random($1)"),
    ("hue\tFunction", "hue($1)"),
    ("saturation\tFunction", "saturation($1)"),
    ("lightness\tFunction", "lightness($1)"),
    ("adjust-hue\tFunction", "adjust-hue($1)"),
    ("lighten\tFunction", "lighten($1)"),
    ("darken\tFunction", "darken($1)"),
    ("saturate\tFunction", "saturate($1)"),
    ("desaturate\tFunction", "desaturate($1)"),
    ("grayscale\tFunction", "grayscale($1)"),
    ("complement\tFunction", "complement($1)"),
    ("invert\tFunction", "invert($1)"),
    ("alpha\tFunction", "alpha($1)"),
    ("opacity\tFunction", "opacity($1)"),
    ("opacify\tFunction", "opacify($1)"),
    ("transparentize\tFunction", "transparentize($1)"),
    ("fade-in\tFunction", "fade-in($1)"),
    ("fade-out\tFunction", "fade-out($1)"),
    ("adjust-color\tFunction", "adjust-color($1)"),
    ("scale-color\tFunction", "scale-color($1)"),
    ("change-color\tFunction", "change-color($1)"),
    ("ie-hex-str\tFunction", "ie-hex-str($1)"),
    ("type-of\tFunction", "type-of($1)"),
    ("unit\tFunction", "unit($1)"),
    ("unitless\tFunction", "unitless($1)"),
    ("comparable\tFunction", "comparable($1)"),
    ("if\tFunction", "if(${1:condition}, $2, $3)"),

    # css defualt value
    ("inherit\tValue", 'inherit'),
    ("initial\tValue", 'initial'),
    ("!important\tValue", '!important'),
    ("!default\tValue", '!default'),
    ("!global\tValue", '!global')
]

# CSS Pseude Class
pseude_class = [
    ("link\tClass", 'link'),
    ("visited\tClass", 'visited'),
    ("active\tClass", 'active'),
    ("hover\tClass", 'hover'),
    ("focus\tClass", 'focus'),
    ("lang\tClass", "lang($1)"),
    ("first-of-type\tClass", 'first-of-type'),
    ("last-of-type\tClass", 'last-of-type'),
    ("only-of-type\tClass", 'only-of-type'),
    ("only-child\tClass", 'only-child'),
    ("nth-child\tClass", "nth-child(${1:1})"),
    ("nth-last-child\tClass", "nth-last-child(${1:1})"),
    ("nth-of-type\tClass", "nth-of-type(${1:1})"),
    ("nth-last-of-type\tClass", "nth-last-of-type(${1:1})"),
    ("last-child\tClass", 'last-child'),
    ("first-child\tClass", 'first-child'),
    ("root\tClass", 'root'),
    ("empty\tClass", 'empty'),
    ("target\tClass", 'target'),
    ("enabled\tClass", 'enabled'),
    ("disabled\tClass", 'disabled'),
    ("checked\tClass", 'checked'),
    ("not\tClass", "not($1)"),

    ("before\tClass", ':before'),
    ("after\tClass", ':after'),
    ("first-letter\tClass", ':first-letter'),
    ("first-line\tClass", ':first-line'),
    ("selection\tClass", ':selection'),

    ("choices\tClass", ':choices'),
    ("frepeat-index\tClass", ':frepeat-index'),
    ("repeat-item\tClass", ':repeat-item'),
    ("value\tClass", ':value'),
    ("placeholder\tClass", ':placeholder')
]

# CSS Extends Style
extends_style = [
    ("charset\trule", "charset \"utf-8\";"),
    ("font-face\trule", "font-face {\n\tfont-family: \"${1:myfont}\";\n\tsrc: url(\"${2:font/myfont}.eot\");\n\tsrc:\n\t\turl(\"${2:font/myfont}.woff\") format(\"woff\"),\n\t\turl(\"${2:font/myfont}.otf\") format(\"opentype\"),\n\t\turl(\"${2:font/myfont}.svg#${1:myfont}\") format(\"svg\");\n}"),
    ("media\trule", "media screen and (min-width: ${1:320}px) and (max-width: ${2:768}px) {$3}"),
    ("keyframes\trule", "keyframes ${1:name} {$2}"),
    ("import\trule", "import \"$0\";"),
    ("import:url\trule", "import url($0);"),
    ("namespace\trule", "namespace \"$0\";"),
    ("namespace:url\trule", "namespace url($0);"),
    ("page\trule", "page ${1::left }{$2}"),
    ("supports\trule", "supports ${1:not }($2) {$3}"),
    ("viewport\trule", "viewport {\n\twidth: device-width;\n\tinitial-scale: 1.0;\n\tmin-scale: 1.0;\n\tmax-scale: 1.0;\n\tuser-zoom: 0;\n}"),

    ("at-root\tSyntax", "at-root"),
    ("debug\tSyntax", "debug $0;"),
    ("error\tSyntax", "error $0;"),
    ("for:to\tSyntax", "for \\$${1:var} from ${2:start} to ${3:end} {$4}"),
    ("for:through\tSyntax", "for \\$${1:var} from ${2:start} through ${3:end} {$4}"),
    ("each\tSyntax", "each \\$${1:var} in \\$${2:list} {$3}"),
    ("return\tSyntax", "return ${0:value};"),
    ("warn\tSyntax", "warn $0;"),
    ("while\tSyntax", "while ${1:condition} {$2}"),
    ("if\tSyntax", "if \\$${1:condition} {$2}"),
    ("else\tSyntax", "else {$1}"),
    ("else if\tSyntax", "else if \\$${1:condition} {$2}"),
    ("content\tSyntax", "content;"),
    ("mixin\tSyntax", "mixin ${1:name}(${2:args}) {$3}"),
    ("function\tSyntax", "function ${1:name}(${2:args}) {$3}"),
    ("include\tSyntax", "include ${0:selector};"),
    ("extend\tSyntax", "extend ${0:selector};")
]

# CSS Keyframes Style
keyframes_style = [
    ("from:to\tKeyframes", "from {$1}\nto {$1}"),
    ("from\tKeyframes", 'from {$1}'),
    ("to\tKeyframes", 'to {$1}')
]
